import { NextResponse } from 'next/server'
import { feedActivationEngine } from '@/lib/agents/feed-activation-engine'

/**
 * GET /api/feed-signals
 *
 * WTEN polls this endpoint (e.g., every 30 seconds) to retrieve any new
 * actions generated by historical agents reacting to the current cosmic weather.
 */
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url)

    // Optional location override, defaults to NYC
    const lat = parseFloat(searchParams.get('lat') || '40.7128')
    const lon = parseFloat(searchParams.get('lon') || '-74.0060')

    // Evaluate activations
    const actions = await feedActivationEngine.evaluateActivations({ lat, lon })

    // In a production system, we would query the database for actions
    // that haven't been fetched yet, mark them as fetched, and return them.
    // For now, we return dynamically evaluated actions.

    return NextResponse.json({
      success: true,
      timestamp: new Date().toISOString(),
      count: actions.length,
      actions,
    })
  } catch (error) {
    console.error('Error generating feed signals:', error)
    return NextResponse.json(
      { success: false, error: 'Failed to generate feed signals' },
      { status: 500 }
    )
  }
}
