[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aae_solana = "5QheuqaicKvPPRFEoEXwaE5xaFp7gauvJCfsjpQv8WzD"

[programs.devnet]
aae_solana = "5QheuqaicKvPPRFEoEXwaE5xaFp7gauvJCfsjpQv8WzD"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bunx vitest run test/solana/esms-persona.spec.ts --config vitest.solana.config.ts"
