import type { ContextCardData } from './types'

export const DEMO_CARD_DATA: ContextCardData = {
  birth: {
    handle: 'Self · Council Native',
    date: 'June 1, 1990',
    time: '10:17 AM',
    tz: 'EDT (UTC−4)',
    utc: '14:17 UTC',
    place: 'Brooklyn, New York, USA',
    lat: '40.6782°N',
    lon: '73.9442°W',
    zodiac: 'Tropical',
    houseSystem: 'Placidus',
    ephemeris: 'Swiss Ephemeris (DE431)',
    bigThree: { sun: 'Gemini', moon: 'Scorpio', rising: 'Leo' },
  },
  points: [
    {
      body: 'Sun',
      kind: 'planet',
      sign: 'Gemini',
      deg: 11.15,
      house: 10,
      retro: false,
      dignity: 'peregrine',
    },
    {
      body: 'Moon',
      kind: 'planet',
      sign: 'Scorpio',
      deg: 23.68,
      house: 4,
      retro: false,
      dignity: 'fall',
    },
    {
      body: 'Mercury',
      kind: 'planet',
      sign: 'Gemini',
      deg: 4.37,
      house: 10,
      retro: false,
      dignity: 'domicile',
    },
    {
      body: 'Venus',
      kind: 'planet',
      sign: 'Cancer',
      deg: 28.83,
      house: 12,
      retro: false,
      dignity: 'peregrine',
    },
    {
      body: 'Mars',
      kind: 'planet',
      sign: 'Virgo',
      deg: 15.27,
      house: 2,
      retro: false,
      dignity: 'peregrine',
    },
    {
      body: 'Jupiter',
      kind: 'planet',
      sign: 'Cancer',
      deg: 18.02,
      house: 11,
      retro: false,
      dignity: 'exaltation',
    },
    {
      body: 'Saturn',
      kind: 'planet',
      sign: 'Capricorn',
      deg: 25.1,
      house: 6,
      retro: true,
      dignity: 'domicile',
    },
    {
      body: 'Uranus',
      kind: 'planet',
      sign: 'Capricorn',
      deg: 8.04,
      house: 5,
      retro: true,
      dignity: 'peregrine',
    },
    {
      body: 'Neptune',
      kind: 'planet',
      sign: 'Capricorn',
      deg: 14.31,
      house: 5,
      retro: true,
      dignity: 'peregrine',
    },
    {
      body: 'Pluto',
      kind: 'planet',
      sign: 'Scorpio',
      deg: 16.05,
      house: 4,
      retro: true,
      dignity: 'domicile',
    },
    { body: 'Ascendant', kind: 'point', sign: 'Leo', deg: 18.0, house: 1, retro: false },
    { body: 'Midheaven', kind: 'point', sign: 'Taurus', deg: 12.17, house: 10, retro: false },
    { body: 'Chiron', kind: 'point', sign: 'Cancer', deg: 16.2, house: 11, retro: false },
    { body: 'North Node', kind: 'point', sign: 'Aquarius', deg: 8.42, house: 6, retro: true },
    { body: 'South Node', kind: 'point', sign: 'Leo', deg: 8.42, house: 12, retro: true },
    { body: 'Lilith', kind: 'point', sign: 'Pisces', deg: 12.06, house: 8, retro: false },
    { body: 'Vertex', kind: 'point', sign: 'Capricorn', deg: 24.4, house: 6, retro: false },
    { body: 'Part of Fortune', kind: 'point', sign: 'Aquarius', deg: 0.52, house: 6, retro: false },
  ],
  houses: [
    { house: 1, sign: 'Leo', deg: 18.0, ruler: 'Sun' },
    { house: 2, sign: 'Virgo', deg: 12.3, ruler: 'Mercury' },
    { house: 3, sign: 'Libra', deg: 9.1, ruler: 'Venus' },
    { house: 4, sign: 'Scorpio', deg: 12.17, ruler: 'Pluto' },
    { house: 5, sign: 'Sagittarius', deg: 16.05, ruler: 'Jupiter' },
    { house: 6, sign: 'Capricorn', deg: 19.22, ruler: 'Saturn' },
    { house: 7, sign: 'Aquarius', deg: 18.0, ruler: 'Uranus' },
    { house: 8, sign: 'Pisces', deg: 12.3, ruler: 'Neptune' },
    { house: 9, sign: 'Aries', deg: 9.1, ruler: 'Mars' },
    { house: 10, sign: 'Taurus', deg: 12.17, ruler: 'Venus' },
    { house: 11, sign: 'Gemini', deg: 16.05, ruler: 'Mercury' },
    { house: 12, sign: 'Cancer', deg: 19.22, ruler: 'Moon' },
  ],
  aspects: [
    { a: 'Moon', b: 'Pluto', type: 'conjunction', orb: 7.6, applying: false, klass: 'major' },
    { a: 'Jupiter', b: 'Chiron', type: 'conjunction', orb: 1.8, applying: true, klass: 'major' },
    { a: 'Uranus', b: 'Neptune', type: 'conjunction', orb: 6.3, applying: true, klass: 'major' },
    { a: 'Moon', b: 'Jupiter', type: 'trine', orb: 5.7, applying: false, klass: 'major' },
    { a: 'Moon', b: 'Venus', type: 'trine', orb: 5.2, applying: true, klass: 'major' },
    { a: 'Mars', b: 'Neptune', type: 'trine', orb: 1.3, applying: true, klass: 'major' },
    { a: 'Moon', b: 'Saturn', type: 'sextile', orb: 1.3, applying: true, klass: 'major' },
    { a: 'Mars', b: 'Pluto', type: 'sextile', orb: 0.7, applying: true, klass: 'major' },
    { a: 'Mars', b: 'Jupiter', type: 'sextile', orb: 2.7, applying: false, klass: 'major' },
    { a: 'Mars', b: 'Chiron', type: 'sextile', orb: 0.7, applying: false, klass: 'major' },
    { a: 'Sun', b: 'Mars', type: 'square', orb: 4.1, applying: true, klass: 'major' },
    { a: 'Venus', b: 'Saturn', type: 'opposition', orb: 3.8, applying: true, klass: 'major' },
    { a: 'Jupiter', b: 'Saturn', type: 'opposition', orb: 7.0, applying: false, klass: 'major' },
    { a: 'Jupiter', b: 'Neptune', type: 'opposition', orb: 3.7, applying: false, klass: 'major' },
    { a: 'Moon', b: 'Ascendant', type: 'square', orb: 5.7, applying: false, klass: 'major' },
    { a: 'Sun', b: 'Neptune', type: 'quincunx', orb: 2.8, applying: true, klass: 'minor' },
    { a: 'Sun', b: 'Saturn', type: 'sesquiquadrate', orb: 1.1, applying: false, klass: 'minor' },
    { a: 'Sun', b: 'Midheaven', type: 'semisextile', orb: 0.9, applying: true, klass: 'minor' },
    { a: 'Venus', b: 'Mars', type: 'semisquare', orb: 1.4, applying: true, klass: 'minor' },
    { a: 'Mercury', b: 'Jupiter', type: 'semisquare', orb: 1.4, applying: false, klass: 'minor' },
  ],
  synthesis: {
    dominantElement: 'Air',
    secondaryElement: 'Water',
    dominantModality: 'Cardinal',
    chartShape: 'Locomotive',
    shapeNote: 'leading planet Mercury in Gemini drives an open trine across Aries–Taurus',
    hemisphere: 'Eastern emphasis — self-directed, identity-led',
    chartRuler: 'Sun (Leo rising) — dispositor chain resolves to Mercury in domicile',
    elementTally: { Fire: 0, Water: 3, Earth: 4, Air: 3 },
    modalityTally: { Cardinal: 3, Fixed: 3, Mutable: 4 },
    signature: 'Mutable Air mind over a Fixed Water depth, anchored by a Cardinal Earth spine',
  },
  alchm: {
    elemental: { Fire: 18, Water: 28, Earth: 24, Air: 30 },
    esms: { spirit: 6, essence: 7, matter: 5, substance: 8 },
    kalchm: 4.12,
    monica: 5.3,
    thermodynamics: { heat: 0.44, entropy: 0.61, reactivity: 0.59, energy: -0.05, aNumber: 5.91 },
    sacred7: {
      power: 62,
      resonance: 74,
      wisdom: 70,
      charisma: 78,
      intuition: 80,
      adaptability: 84,
      vitality: 68,
    },
    planetary12: {
      solarAgency: 60,
      lunarReceptivity: 84,
      mercurialVelocity: 86,
      venusianCoherence: 76,
      martialImpetus: 58,
      jovianExpansion: 70,
      saturnianStructure: 64,
      chironicAdaptation: 78,
      uranianSurprisal: 72,
      neptunianResonance: 80,
      plutonicIntegration: 76,
      kineticAlignment: 70,
    },
    note:
      'alchm.kitchen derives these from the natal chart via lib/alchemizer + lib/agents/*. ' +
      'ESMS = Spirit/Essence/Matter/Substance. Kalchm & Monica are alchm equilibrium constants. ' +
      'Thermodynamics: Energy = Heat − Reactivity×Entropy; A# = total alchemical power.',
  },
  synopsis: [
    'A Gemini Sun in the 10th house gives a public, communicative identity that thinks out loud and works in the open — but it sits over a Scorpio Moon conjunct Pluto in the 4th, a private emotional depth that runs far beneath the quick surface. Leo rising wraps the whole package in visible warmth and easy confidence.',
    'The chart is a Locomotive driven by Mercury in its own sign: the mind leads. A Cardinal-Earth spine (Saturn, Uranus and Neptune in Capricorn across the 5th–6th) supplies discipline and stamina, while a very tight Mars–Pluto–Chiron web — Mars sextile both within a degree — channels regenerative force into craft and work. Venus opposite Saturn asks for intimacy that is earned rather than given.',
    'In alchm terms the profile reads Air-led (30%) over Water (28%): a thinking nature with deep feeling underneath. High Substance (8) and Adaptability (84) make this a resilient, shape-shifting operator, and a Kalchm of 4.12 against a Monica of 5.3 marks a stable, slightly cool equilibrium — quick to reconfigure, slow to burn out.',
  ],
}
