import type { ContextCardData, ExportOptions, ExportFormat, ContextCardPlacement } from './types'
import { ASPECT_SYMBOLS, ASPECT_ANGLES, BODY_GLYPHS } from './types'

export function fmtDegree(d: number): string {
  const deg = Math.floor(d)
  const min = Math.round((d - deg) * 60)
  const dd = min === 60 ? deg + 1 : deg
  const mm = min === 60 ? 0 : min
  return `${dd}°${String(mm).padStart(2, '0')}'`
}

const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1)
const motion = (p: ContextCardPlacement) => (p.retro ? 'Rx' : 'direct')
const spaced = (k: string) => k.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())

const SIGN_KEY: Record<string, string> = {
  Aries: 'initiative and raw drive',
  Taurus: 'stability and the senses',
  Gemini: 'curiosity and language',
  Cancer: 'nurture and emotional security',
  Leo: 'self-expression and warmth',
  Virgo: 'analysis and refinement',
  Libra: 'balance and relating',
  Scorpio: 'depth, intensity and control',
  Sagittarius: 'expansion and meaning',
  Capricorn: 'structure and ambition',
  Aquarius: 'innovation and detachment',
  Pisces: 'imagination and empathy',
}
const HOUSE_KEY: Record<number, string> = {
  1: 'identity and the body',
  2: 'resources, money and values',
  3: 'mind, siblings and communication',
  4: 'home, family and roots',
  5: 'creativity, play and romance',
  6: 'work, routine and health',
  7: 'partnership and the other',
  8: 'intimacy, shared resources and transformation',
  9: 'philosophy, travel and belief',
  10: 'career, vocation and public role',
  11: 'community, friends and hopes',
  12: 'the unconscious, retreat and the hidden',
}
const BODY_KEY: Record<string, string> = {
  Sun: 'core identity and vitality',
  Moon: 'emotional needs and instinct',
  Mercury: 'thinking and speech',
  Venus: 'love, taste and values',
  Mars: 'drive, desire and assertion',
  Jupiter: 'growth, faith and luck',
  Saturn: 'discipline, limits and time',
  Uranus: 'freedom and disruption',
  Neptune: 'dreams and dissolution',
  Pluto: 'power, depth and rebirth',
  Chiron: 'the core wound and its healing gift',
  'North Node': 'soul growth direction',
  'South Node': 'innate gifts and the comfort zone',
  Lilith: 'the raw, untamed self',
  Ascendant: 'outward style and approach',
  Midheaven: 'vocation, reputation and the public peak',
  Vertex: 'fated encounters and turning points',
  'Part of Fortune': 'where ease and flourishing come naturally',
}

function gloss(p: ContextCardPlacement): string {
  const body = BODY_KEY[p.body] || p.body
  const sign = SIGN_KEY[p.sign] || p.sign
  const house = HOUSE_KEY[p.house] || `house ${p.house}`
  return `${body}, expressed through ${sign}, in the field of ${house}`
}

const PROMPT_HEADER = `You are a perceptive, grounded astrological advisor. Attached below is the COMPLETE natal
chart and alchm energetic profile of the person you are advising. Use ALL of it — the
placements, house cusps, the full aspect grid, the dominant patterns, and the alchm layer —
to give specific, personalized guidance. Always reason from named chart factors (e.g. "your
Moon–Pluto conjunction in the 4th") rather than generic sun-sign advice. When asked about
timing, work, relationships, money, or wellbeing, ground every recommendation in the relevant
placements. Be honest about hard aspects; frame them as workable tension, not fate.`

function aspectsFor(data: ContextCardData, opts: ExportOptions) {
  return data.aspects.filter(a => opts.minorAspects || a.klass === 'major')
}

function buildMarkdown(data: ContextCardData, opts: ExportOptions): string {
  const L: string[] = []
  const bt = data.birth.bigThree
  L.push('# ASTROLOGICAL CONTEXT CARD')
  L.push('<!-- Generated by alchm.kitchen · Cosmic Agents — attach this file to any LLM. -->')
  L.push('')

  if (opts.promptHeader) {
    L.push('## HOW TO USE THIS FILE')
    L.push(PROMPT_HEADER)
    L.push('')
  }

  L.push('## SUBJECT')
  L.push(`- Handle: ${data.birth.handle}`)
  L.push(`- Born: ${data.birth.date}, ${data.birth.time} ${data.birth.tz}  (${data.birth.utc})`)
  L.push(`- Place: ${data.birth.place} — ${data.birth.lat}, ${data.birth.lon}`)
  L.push(
    `- System: ${data.birth.zodiac} zodiac · ${data.birth.houseSystem} houses · ${data.birth.ephemeris}`
  )
  L.push('')

  L.push('## CORE SIGNATURE (BIG THREE)')
  L.push(`- **Sun** in ${bt.sun} — conscious identity`)
  L.push(`- **Moon** in ${bt.moon} — emotional nature`)
  L.push(`- **Rising / Ascendant** in ${bt.rising} — outward style`)
  L.push('')

  if (opts.synopsis && data.synopsis.length) {
    L.push('## SYNOPSIS')
    data.synopsis.forEach(p => {
      L.push(p)
      L.push('')
    })
  }

  const planets = data.points.filter(p => p.kind === 'planet')
  const points = data.points.filter(p => p.kind === 'point')

  L.push('## PLANETARY PLACEMENTS')
  L.push('| Body | Sign | Degree | House | Motion | Dignity |')
  L.push('|------|------|--------|-------|--------|---------|')
  planets.forEach(p => {
    L.push(
      `| ${p.body} | ${p.sign} | ${fmtDegree(p.deg)} | ${p.house} | ${motion(p)} | ${cap(p.dignity || 'peregrine')} |`
    )
  })
  if (opts.annotated) {
    L.push('')
    planets.forEach(p => L.push(`- ${BODY_GLYPHS[p.body] || ''} ${p.body}: ${gloss(p)}.`))
  }
  L.push('')

  if (points.length) {
    L.push('## ANGLES & POINTS')
    L.push('| Point | Sign | Degree | House |')
    L.push('|-------|------|--------|-------|')
    points.forEach(p => L.push(`| ${p.body} | ${p.sign} | ${fmtDegree(p.deg)} | ${p.house} |`))
    if (opts.annotated) {
      L.push('')
      points.forEach(p => L.push(`- ${p.body}: ${gloss(p)}.`))
    }
    L.push('')
  }

  if (opts.houses && data.houses.length) {
    L.push(`## HOUSE CUSPS (${data.birth.houseSystem})`)
    L.push('| House | Cusp | Ruler |')
    L.push('|-------|------|-------|')
    data.houses.forEach(h => L.push(`| ${h.house} | ${h.sign} ${fmtDegree(h.deg)} | ${h.ruler} |`))
    L.push('')
  }

  const mdAspectList = aspectsFor(data, opts)
  if (opts.aspects && mdAspectList.length) {
    const list = mdAspectList
    const major = list.filter(a => a.klass === 'major')
    const minor = list.filter(a => a.klass === 'minor')
    L.push('## ASPECTS')
    L.push('### Major')
    major.forEach(a => {
      L.push(
        `- ${a.a} ${ASPECT_SYMBOLS[a.type] || ''} ${a.b} — ${a.type} (${ASPECT_ANGLES[a.type] || 0}°), orb ${a.orb}°, ${a.applying ? 'applying' : 'separating'}`
      )
    })
    if (minor.length) {
      L.push('### Minor')
      minor.forEach(a => {
        L.push(
          `- ${a.a} ${ASPECT_SYMBOLS[a.type] || ''} ${a.b} — ${a.type} (${ASPECT_ANGLES[a.type] || 0}°), orb ${a.orb}°, ${a.applying ? 'applying' : 'separating'}`
        )
      })
    }
    L.push('')
  }

  L.push('## CHART SYNTHESIS')
  L.push(
    `- Dominant element: ${data.synthesis.dominantElement} (then ${data.synthesis.secondaryElement})`
  )
  const et = data.synthesis.elementTally,
    mt = data.synthesis.modalityTally
  L.push(
    `- Element tally (10 planets): Fire ${et.Fire} · Earth ${et.Earth} · Air ${et.Air} · Water ${et.Water}`
  )
  L.push(
    `- Dominant modality: ${data.synthesis.dominantModality} (Cardinal ${mt.Cardinal} · Fixed ${mt.Fixed} · Mutable ${mt.Mutable})`
  )
  L.push(`- Chart shape: ${data.synthesis.chartShape} — ${data.synthesis.shapeNote}`)
  L.push(`- Hemisphere: ${data.synthesis.hemisphere}`)
  L.push(`- Chart ruler: ${data.synthesis.chartRuler}`)
  L.push(`- Signature: ${data.synthesis.signature}`)
  L.push('')

  if (opts.transits && data.transits) {
    const m = data.transits.meta
    L.push('## CURRENT SKY — TRANSIT SYNERGY')
    L.push(`- Moment: ${m.when}${m.location ? ' · ' + m.location : ''}`)
    L.push(
      `- Planetary hour: ${m.planetaryHour} · Moon: ${m.moonPhase} (${Math.round((m.moonIllumination || 0) * 100)}%) · Sky ruler: ${m.dominantPlanet} in ${m.dominantSign}`
    )
    L.push('')
    L.push('### Transit → natal aspects (tightest first)')
    data.transits.aspects.forEach(a =>
      L.push(`- transiting ${a.t}${a.tRetro ? ' ℞' : ''} ${a.type} natal ${a.n} — orb ${a.orb}°`)
    )
    L.push('')
  }

  if (opts.alchm) {
    const e = data.alchm.elemental,
      q = data.alchm.esms,
      t = data.alchm.thermodynamics
    L.push('## ALCHM LAYER — alchm.kitchen proprietary')
    L.push('### Elemental balance (weighted)')
    L.push(`Fire ${e.Fire}% · Water ${e.Water}% · Earth ${e.Earth}% · Air ${e.Air}%`)
    L.push('### ESMS — Alchemy quad')
    L.push(
      `Spirit ${q.spirit} · Essence ${q.essence} · Matter ${q.matter} · Substance ${q.substance}`
    )
    L.push('### Equilibrium constants')
    L.push(`Kalchm ${data.alchm.kalchm} · Monica ${data.alchm.monica}`)
    L.push('### Thermodynamics')
    L.push(
      `Heat ${t.heat} · Entropy ${t.entropy} · Reactivity ${t.reactivity} · Energy ${t.energy} · A# ${t.aNumber}`
    )
    if (Object.keys(data.alchm.sacred7).length) {
      L.push('### Sacred 7')
      L.push(
        Object.entries(data.alchm.sacred7)
          .map(([k, v]) => `${cap(k)} ${v}`)
          .join(' · ')
      )
    }
    if (Object.keys(data.alchm.planetary12).length) {
      L.push('### Planetary 12')
      L.push(
        Object.entries(data.alchm.planetary12)
          .map(([k, v]) => `${spaced(k)} ${v}`)
          .join(' · ')
      )
    }
    if (opts.annotated) {
      L.push('')
      L.push(`> ${data.alchm.note}`)
    }
    L.push('')
  }

  L.push('<!-- END CONTEXT CARD -->')
  return L.join('\n')
}

function pad(s: string, n: number): string {
  return s + ' '.repeat(Math.max(0, n - s.length))
}
function rule(ch = '='): string {
  return ch.repeat(60)
}

function buildText(data: ContextCardData, opts: ExportOptions): string {
  const L: string[] = []
  const bt = data.birth.bigThree
  const planets = data.points.filter(p => p.kind === 'planet')
  const points = data.points.filter(p => p.kind === 'point')

  L.push(rule('='))
  L.push('  ASTROLOGICAL CONTEXT CARD')
  L.push('  alchm.kitchen / Cosmic Agents')
  L.push(rule('='))
  L.push('')

  if (opts.promptHeader) {
    L.push('HOW TO USE THIS FILE')
    L.push(rule('-'))
    L.push(PROMPT_HEADER)
    L.push('')
  }

  L.push('SUBJECT')
  L.push(rule('-'))
  L.push(`Handle : ${data.birth.handle}`)
  L.push(`Born   : ${data.birth.date}, ${data.birth.time} ${data.birth.tz}  (${data.birth.utc})`)
  L.push(`Place  : ${data.birth.place} (${data.birth.lat}, ${data.birth.lon})`)
  L.push(
    `System : ${data.birth.zodiac} zodiac, ${data.birth.houseSystem} houses, ${data.birth.ephemeris}`
  )
  L.push('')

  L.push('CORE SIGNATURE (BIG THREE)')
  L.push(rule('-'))
  L.push(`Sun     : ${bt.sun}    (conscious identity)`)
  L.push(`Moon    : ${bt.moon}   (emotional nature)`)
  L.push(`Rising  : ${bt.rising} (outward style)`)
  L.push('')

  if (opts.synopsis && data.synopsis.length) {
    L.push('SYNOPSIS')
    L.push(rule('-'))
    data.synopsis.forEach(p => {
      L.push(p)
      L.push('')
    })
  }

  L.push('PLANETARY PLACEMENTS')
  L.push(rule('-'))
  L.push(
    `${pad('BODY', 9)}${pad('SIGN', 13)}${pad('DEGREE', 9)}${pad('HOUSE', 7)}${pad('MOTION', 8)}DIGNITY`
  )
  planets.forEach(p => {
    L.push(
      `${pad(p.body, 9)}${pad(p.sign, 13)}${pad(fmtDegree(p.deg), 9)}${pad(String(p.house), 7)}${pad(motion(p), 8)}${cap(p.dignity || 'peregrine')}`
    )
  })
  if (opts.annotated) {
    L.push('')
    planets.forEach(p => L.push(`  - ${p.body}: ${gloss(p)}.`))
  }
  L.push('')

  if (points.length) {
    L.push('ANGLES & POINTS')
    L.push(rule('-'))
    L.push(`${pad('POINT', 18)}${pad('SIGN', 13)}${pad('DEGREE', 9)}HOUSE`)
    points.forEach(p =>
      L.push(`${pad(p.body, 18)}${pad(p.sign, 13)}${pad(fmtDegree(p.deg), 9)}${p.house}`)
    )
    L.push('')
  }

  if (opts.houses && data.houses.length) {
    L.push(`HOUSE CUSPS (${data.birth.houseSystem})`)
    L.push(rule('-'))
    data.houses.forEach(h =>
      L.push(
        `${pad('House ' + h.house, 10)}${pad(h.sign + ' ' + fmtDegree(h.deg), 18)}ruler: ${h.ruler}`
      )
    )
    L.push('')
  }

  const txtAspectList = aspectsFor(data, opts)
  if (opts.aspects && txtAspectList.length) {
    const list = txtAspectList
    L.push('ASPECTS')
    L.push(rule('-'))
    list.forEach(a => {
      const tag = a.klass === 'minor' ? '[minor] ' : ''
      L.push(
        `${tag}${pad(a.a, 9)}${pad(a.type, 16)}${pad(a.b, 10)} orb ${a.orb} deg, ${a.applying ? 'applying' : 'separating'}`
      )
    })
    L.push('')
  }

  L.push('CHART SYNTHESIS')
  L.push(rule('-'))
  const et = data.synthesis.elementTally,
    mt = data.synthesis.modalityTally
  L.push(
    `Dominant element : ${data.synthesis.dominantElement} (then ${data.synthesis.secondaryElement})`
  )
  L.push(`Element tally    : Fire ${et.Fire}, Earth ${et.Earth}, Air ${et.Air}, Water ${et.Water}`)
  L.push(
    `Dominant modality: ${data.synthesis.dominantModality} (Cardinal ${mt.Cardinal}, Fixed ${mt.Fixed}, Mutable ${mt.Mutable})`
  )
  L.push(`Chart shape      : ${data.synthesis.chartShape} - ${data.synthesis.shapeNote}`)
  L.push(`Hemisphere       : ${data.synthesis.hemisphere}`)
  L.push(`Chart ruler      : ${data.synthesis.chartRuler}`)
  L.push(`Signature        : ${data.synthesis.signature}`)
  L.push('')

  if (opts.transits && data.transits) {
    const m = data.transits.meta
    L.push('CURRENT SKY - TRANSIT SYNERGY')
    L.push(rule('-'))
    L.push(`Moment : ${m.when}${m.location ? ' (' + m.location + ')' : ''}`)
    L.push(
      `Sky    : ${m.planetaryHour} hour, ${m.moonPhase} Moon ${Math.round((m.moonIllumination || 0) * 100)}%, ruler ${m.dominantPlanet} in ${m.dominantSign}`
    )
    L.push('')
    L.push('Transit -> natal aspects (tightest first):')
    data.transits.aspects.forEach(a =>
      L.push(
        `  t.${pad(a.t + (a.tRetro ? ' Rx' : ''), 12)}${pad(a.type, 14)}n.${pad(a.n, 12)} orb ${a.orb} deg`
      )
    )
    L.push('')
  }

  if (opts.alchm) {
    const e = data.alchm.elemental,
      q = data.alchm.esms,
      t = data.alchm.thermodynamics
    L.push('ALCHM LAYER (alchm.kitchen proprietary)')
    L.push(rule('-'))
    L.push(`Elemental : Fire ${e.Fire}%, Water ${e.Water}%, Earth ${e.Earth}%, Air ${e.Air}%`)
    L.push(
      `ESMS      : Spirit ${q.spirit}, Essence ${q.essence}, Matter ${q.matter}, Substance ${q.substance}`
    )
    L.push(`Constants : Kalchm ${data.alchm.kalchm}, Monica ${data.alchm.monica}`)
    L.push(
      `Thermo    : Heat ${t.heat}, Entropy ${t.entropy}, Reactivity ${t.reactivity}, Energy ${t.energy}, A# ${t.aNumber}`
    )
    if (Object.keys(data.alchm.sacred7).length) {
      L.push(
        `Sacred 7  : ${Object.entries(data.alchm.sacred7)
          .map(([k, v]) => cap(k) + ' ' + v)
          .join(', ')}`
      )
    }
    if (Object.keys(data.alchm.planetary12).length) {
      L.push(
        `Planet 12 : ${Object.entries(data.alchm.planetary12)
          .map(([k, v]) => spaced(k) + ' ' + v)
          .join(', ')}`
      )
    }
    if (opts.annotated) {
      L.push('')
      L.push(data.alchm.note)
    }
    L.push('')
  }

  L.push(rule('='))
  L.push('  END CONTEXT CARD')
  L.push(rule('='))
  return L.join('\n')
}

function buildJSON(data: ContextCardData, opts: ExportOptions): string {
  const planets = data.points.filter(p => p.kind === 'planet')
  const points = data.points.filter(p => p.kind === 'point')

  const obj: Record<string, unknown> = {
    _meta: {
      schema: 'alchm.context-card/v1',
      generator: 'alchm.kitchen · Cosmic Agents',
      attach_to: 'any LLM (ChatGPT, Claude, Gemini, …) as context',
    },
    subject: {
      handle: data.birth.handle,
      born: {
        date: data.birth.date,
        time: data.birth.time,
        tz: data.birth.tz,
        utc: data.birth.utc,
      },
      place: data.birth.place,
      lat: data.birth.lat,
      lon: data.birth.lon,
      zodiac: data.birth.zodiac,
      house_system: data.birth.houseSystem,
      ephemeris: data.birth.ephemeris,
      big_three: data.birth.bigThree,
    },
    placements: planets.map(p => ({
      body: p.body,
      sign: p.sign,
      degree: fmtDegree(p.deg),
      decimal: p.deg,
      house: p.house,
      retrograde: p.retro,
      dignity: p.dignity,
      ...(opts.annotated ? { note: gloss(p) } : {}),
    })),
    synthesis: {
      dominant_element: data.synthesis.dominantElement,
      secondary_element: data.synthesis.secondaryElement,
      element_tally: data.synthesis.elementTally,
      dominant_modality: data.synthesis.dominantModality,
      modality_tally: data.synthesis.modalityTally,
      chart_shape: data.synthesis.chartShape,
      shape_note: data.synthesis.shapeNote,
      hemisphere: data.synthesis.hemisphere,
      chart_ruler: data.synthesis.chartRuler,
      signature: data.synthesis.signature,
    },
  }

  if (points.length) {
    obj.points = points.map(p => ({
      point: p.body,
      sign: p.sign,
      degree: fmtDegree(p.deg),
      decimal: p.deg,
      house: p.house,
      ...(opts.annotated ? { note: gloss(p) } : {}),
    }))
  }
  if (opts.synopsis && data.synopsis.length) obj.synopsis = data.synopsis
  if (opts.promptHeader) obj.how_to_use = PROMPT_HEADER
  if (opts.houses && data.houses.length) {
    obj.house_cusps = data.houses.map(h => ({
      house: h.house,
      sign: h.sign,
      degree: fmtDegree(h.deg),
      decimal: h.deg,
      ruler: h.ruler,
    }))
  }
  const jsonAspectList = aspectsFor(data, opts)
  if (opts.aspects && jsonAspectList.length) {
    obj.aspects = jsonAspectList.map(a => ({
      a: a.a,
      b: a.b,
      type: a.type,
      angle: ASPECT_ANGLES[a.type] || 0,
      orb: a.orb,
      applying: a.applying,
      class: a.klass,
    }))
  }
  if (opts.transits && data.transits) {
    const m = data.transits.meta
    obj.current_sky = {
      moment: m.when,
      location: m.location,
      planetary_hour: m.planetaryHour,
      moon_phase: m.moonPhase,
      moon_illumination: m.moonIllumination,
      sky_ruler: m.dominantPlanet + ' in ' + m.dominantSign,
      transit_aspects: data.transits.aspects.map(a => ({
        transit: a.t,
        retrograde: !!a.tRetro,
        type: a.type,
        natal: a.n,
        orb: a.orb,
      })),
    }
  }
  if (opts.alchm) {
    obj.alchm = {
      elemental_pct: data.alchm.elemental,
      esms: data.alchm.esms,
      kalchm: data.alchm.kalchm,
      monica: data.alchm.monica,
      thermodynamics: data.alchm.thermodynamics,
      ...(Object.keys(data.alchm.sacred7).length ? { sacred7: data.alchm.sacred7 } : {}),
      ...(Object.keys(data.alchm.planetary12).length
        ? { planetary12: data.alchm.planetary12 }
        : {}),
      ...(opts.annotated ? { note: data.alchm.note } : {}),
    }
  }

  if (opts.promptHeader) {
    const { how_to_use, _meta, ...rest } = obj
    return JSON.stringify({ _meta, how_to_use, ...rest }, null, 2)
  }
  return JSON.stringify(obj, null, 2)
}

export function buildOutput(
  data: ContextCardData,
  format: ExportFormat,
  opts: ExportOptions
): string {
  if (format === 'txt') return buildText(data, opts)
  if (format === 'json') return buildJSON(data, opts)
  return buildMarkdown(data, opts)
}
