import type { ContextCardData, ExportOptions, ExportFormat, ContextCardPlacement } from './types'
import { ASPECT_SYMBOLS, ASPECT_ANGLES, BODY_GLYPHS } from './types'

export function fmtDegree(d: number): string {
  const deg = Math.floor(d)
  const min = Math.round((d - deg) * 60)
  const dd = min === 60 ? deg + 1 : deg
  const mm = min === 60 ? 0 : min
  return `${dd}°${String(mm).padStart(2, '0')}'`
}

const cap = (s: string) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : '')
const motion = (p: ContextCardPlacement) => (p.retro ? 'Rx' : 'direct')
const formatHouse = (h: number) => (h && h > 0 ? h : 'N/A')
const spaced = (k: string) => k.replace(/([A-Z])/g, ' $1').replace(/^./, c => c.toUpperCase())

const SIGN_KEY: Record<string, string> = {
  Aries: 'initiative and raw drive',
  Taurus: 'stability and the senses',
  Gemini: 'curiosity and language',
  Cancer: 'nurture and emotional security',
  Leo: 'self-expression and warmth',
  Virgo: 'analysis and refinement',
  Libra: 'balance and relating',
  Scorpio: 'depth, intensity and control',
  Sagittarius: 'expansion and meaning',
  Capricorn: 'structure and ambition',
  Aquarius: 'innovation and detachment',
  Pisces: 'imagination and empathy',
}
const HOUSE_KEY: Record<number, string> = {
  1: 'identity and the body',
  2: 'resources, money and values',
  3: 'mind, siblings and communication',
  4: 'home, family and roots',
  5: 'creativity, play and romance',
  6: 'work, routine and health',
  7: 'partnership and the other',
  8: 'intimacy, shared resources and transformation',
  9: 'philosophy, travel and belief',
  10: 'career, vocation and public role',
  11: 'community, friends and hopes',
  12: 'the unconscious, retreat and the hidden',
}
const BODY_KEY: Record<string, string> = {
  Sun: 'core identity and vitality',
  Moon: 'emotional needs and instinct',
  Mercury: 'thinking and speech',
  Venus: 'love, taste and values',
  Mars: 'drive, desire and assertion',
  Jupiter: 'growth, faith and luck',
  Saturn: 'discipline, limits and time',
  Uranus: 'freedom and disruption',
  Neptune: 'dreams and dissolution',
  Pluto: 'power, depth and rebirth',
  Chiron: 'the core wound and its healing gift',
  'North Node': 'soul growth direction',
  'South Node': 'innate gifts and the comfort zone',
  Lilith: 'the raw, untamed self',
  Ascendant: 'outward style and approach',
  Midheaven: 'vocation, reputation and the public peak',
  Vertex: 'fated encounters and turning points',
  'Part of Fortune': 'where ease and flourishing come naturally',
}

function gloss(p: ContextCardPlacement): string {
  const body = BODY_KEY[p.body] || p.body
  const sign = SIGN_KEY[p.sign] || p.sign
  const houseStr = p.house && p.house > 0 ? HOUSE_KEY[p.house] || `house ${p.house}` : 'the sky'
  return `${body}, expressed through ${sign}, in ${houseStr}`
}

const PROMPT_HEADER = `You are a perceptive, grounded astrological advisor. Attached below is the natal chart and alchm energetic profile of the person you are advising. Use ALL of it — the placements, house cusps, the full aspect grid, the dominant patterns, and the alchm layer — to give specific, personalized guidance. Always reason from named chart factors (e.g. "your Moon–Pluto aspect") rather than generic advice. When asked about timing, work, relationships, or wellbeing, ground every recommendation in the relevant placements. Be honest about hard aspects; frame them as workable tension, not fate.`

function aspectsFor(data: ContextCardData, opts: ExportOptions) {
  return data.aspects.filter(a => opts.minorAspects || a.klass === 'major')
}

function buildMarkdown(data: ContextCardData, opts: ExportOptions): string {
  const L: string[] = []
  const bt = data.birth.bigThree
  L.push('# ASTROLOGICAL CONTEXT CARD')
  L.push('<!-- Generated by alchm.kitchen · Cosmic Agents — attach this file to any LLM. -->')
  L.push('')

  if (opts.promptHeader) {
    L.push('## HOW TO USE THIS FILE')
    L.push(PROMPT_HEADER)
    L.push('')
  }

  L.push('## DATA PROVENANCE & METHODOLOGY')
  L.push(`- Engine: ${data.birth.ephemeris || 'VSOP87 / High-Precision Astronomical Ephemeris'}`)
  L.push(`- Zodiac / House System: ${data.birth.zodiac} · ${data.birth.houseSystem}`)
  L.push(`- Timezone / UTC Conversion: ${data.birth.tz} (${data.birth.utc})`)
  L.push(
    '- Calculation Integrity: All aspect orbs and dignities derived from 0–360° normalized ecliptic longitudes.'
  )
  L.push(
    '- Symbolic Notice: Astrological metrics and Sacred 7 scores are symbolic alchemical frameworks intended for personal reflection.'
  )
  L.push('')

  L.push('## SUBJECT')
  L.push(`- Handle: ${data.birth.handle}`)
  L.push(`- Born: ${data.birth.date}, ${data.birth.time} ${data.birth.tz} (${data.birth.utc})`)
  L.push(`- Place: ${data.birth.place} — ${data.birth.lat}, ${data.birth.lon}`)
  L.push('')

  L.push('## CORE SIGNATURE (BIG THREE)')
  L.push(`- **Sun** in ${bt.sun} — conscious identity`)
  L.push(`- **Moon** in ${bt.moon} — emotional nature`)
  L.push(`- **Rising / Ascendant** in ${bt.rising} — outward style`)
  L.push('')

  if (opts.synopsis && data.synopsis && data.synopsis.length) {
    L.push('## SYNOPSIS')
    data.synopsis.forEach(p => {
      L.push(p)
      L.push('')
    })
  }

  const planets = (data.points || []).filter(p => p.kind === 'planet')
  const points = (data.points || []).filter(p => p.kind === 'point')

  L.push('## PLANETARY PLACEMENTS')
  L.push('| Body | Sign | Degree | House | Motion | Dignity |')
  L.push('|------|------|--------|-------|--------|---------|')
  planets.forEach(p => {
    L.push(
      `| ${p.body} | ${p.sign} | ${fmtDegree(p.deg)} | ${formatHouse(p.house)} | ${motion(p)} | ${cap(p.dignity || 'peregrine')} |`
    )
  })
  if (opts.annotated && planets.length) {
    L.push('')
    planets.forEach(p => L.push(`- ${BODY_GLYPHS[p.body] || ''} ${p.body}: ${gloss(p)}.`))
  }
  L.push('')

  if (points.length > 0) {
    L.push('## ANGLES & POINTS')
    L.push('| Point | Sign | Degree | House |')
    L.push('|-------|------|--------|-------|')
    points.forEach(p =>
      L.push(`| ${p.body} | ${p.sign} | ${fmtDegree(p.deg)} | ${formatHouse(p.house)} |`)
    )
    if (opts.annotated) {
      L.push('')
      points.forEach(p => L.push(`- ${p.body}: ${gloss(p)}.`))
    }
    L.push('')
  }

  if (opts.houses && data.houses && data.houses.length > 0) {
    L.push(`## HOUSE CUSPS (${data.birth.houseSystem})`)
    L.push('| House | Cusp | Ruler |')
    L.push('|-------|------|-------|')
    data.houses.forEach(h => L.push(`| ${h.house} | ${h.sign} ${fmtDegree(h.deg)} | ${h.ruler} |`))
    L.push('')
  }

  const mdAspectList = aspectsFor(data, opts)
  if (opts.aspects && mdAspectList.length > 0) {
    const list = mdAspectList
    const major = list.filter(a => a.klass === 'major')
    const minor = list.filter(a => a.klass === 'minor')
    L.push('## ASPECTS')
    if (major.length) {
      L.push('### Major')
      major.forEach(a => {
        L.push(
          `- ${a.a} ${ASPECT_SYMBOLS[a.type] || ''} ${a.b} — ${a.type} (${ASPECT_ANGLES[a.type] || 0}°), orb ${a.orb}°, ${a.applying ? 'applying' : 'separating'}`
        )
      })
    }
    if (minor.length) {
      L.push('### Minor')
      minor.forEach(a => {
        L.push(
          `- ${a.a} ${ASPECT_SYMBOLS[a.type] || ''} ${a.b} — ${a.type} (${ASPECT_ANGLES[a.type] || 0}°), orb ${a.orb}°, ${a.applying ? 'applying' : 'separating'}`
        )
      })
    }
    L.push('')
  }

  L.push('## CHART SYNTHESIS')
  L.push(
    `- Dominant element: ${data.synthesis.dominantElement} (then ${data.synthesis.secondaryElement})`
  )
  const et = data.synthesis.elementTally,
    mt = data.synthesis.modalityTally
  L.push(
    `- Element tally (10 planets): Fire ${et.Fire ?? 0} · Earth ${et.Earth ?? 0} · Air ${et.Air ?? 0} · Water ${et.Water ?? 0}`
  )
  L.push(
    `- Dominant modality: ${data.synthesis.dominantModality} (Cardinal ${mt.Cardinal ?? 0} · Fixed ${mt.Fixed ?? 0} · Mutable ${mt.Mutable ?? 0})`
  )
  L.push(`- Chart shape: ${data.synthesis.chartShape} — ${data.synthesis.shapeNote}`)
  L.push(`- Hemisphere: ${data.synthesis.hemisphere}`)
  L.push(`- Chart ruler: ${data.synthesis.chartRuler}`)
  L.push(`- Signature: ${data.synthesis.signature}`)
  if (data.synthesis.signComposition && Object.keys(data.synthesis.signComposition).length > 0) {
    const compStr = Object.entries(data.synthesis.signComposition)
      .sort((a, b) => b[1] - a[1])
      .map(([s, pct]) => `${s} ${pct}%`)
      .join(' · ')
    L.push(`- Zodiac sign composition: ${compStr}`)
  }
  if (
    data.synthesis.weightedSignComposition &&
    Object.keys(data.synthesis.weightedSignComposition).length > 0
  ) {
    const wCompStr = Object.entries(data.synthesis.weightedSignComposition)
      .sort((a, b) => b[1] - a[1])
      .map(([s, pct]) => `${s} ${pct}%`)
      .join(' · ')
    L.push(`- Weighted sign character: ${wCompStr}`)
  }
  L.push('')

  if (opts.transits && data.transits) {
    const m = data.transits.meta
    L.push('## CURRENT SKY — TRANSIT SYNERGY')
    L.push(`- Calculated: ${m.when}`)
    L.push(`- Observer: ${m.location}`)
    L.push(`- Planetary hour: ${m.planetaryHour}`)
    L.push(
      `- Moon phase: ${m.moonPhase} (${Math.round((m.moonIllumination || 0) * 100)}% illuminated)`
    )
    L.push(`- Dominant sky theme: ${m.dominantPlanet} in ${m.dominantSign}`)
    L.push('')
    if (data.transits.aspects && data.transits.aspects.length) {
      L.push('### Active Transit Contacts')
      L.push('| Transit Planet | Aspect | Natal Target | Orb | Contact |')
      L.push('|----------------|--------|--------------|-----|---------|')
      data.transits.aspects.forEach(a => {
        L.push(
          `| ${a.t}${a.tRetro ? ' (Rx)' : ''} | ${a.type} | ${a.n} | ${a.orb}° | ${a.applying ? 'applying' : 'separating'} |`
        )
      })
      L.push('')
    }
  }

  if (opts.alchm) {
    L.push('## ALCHM LAYER')
    const es = data.alchm.esms
    L.push(
      `- ESMS Balance: Spirit ${es.spirit} · Essence ${es.essence} · Matter ${es.matter} · Substance ${es.substance}`
    )
    L.push(`- Kalchm Quotient: ${data.alchm.kalchm}`)
    L.push(`- Monica Constant: ${data.alchm.monica}`)
    L.push('')
    if (data.alchm.sacred7 && Object.keys(data.alchm.sacred7).length > 0) {
      L.push('### Sacred 7 Scores')
      Object.entries(data.alchm.sacred7).forEach(([k, v]) => {
        L.push(`- ${spaced(k)}: ${v}/100`)
      })
      L.push('')
    }
    if (data.alchm.planetary12 && Object.keys(data.alchm.planetary12).length > 0) {
      L.push('### Planetary 12 Scores')
      Object.entries(data.alchm.planetary12).forEach(([k, v]) => {
        L.push(`- ${spaced(k)}: ${v}/100`)
      })
      L.push('')
    }
  }

  L.push('<!-- END CONTEXT CARD -->')
  return L.join('\n')
}

function buildText(data: ContextCardData, opts: ExportOptions): string {
  const L: string[] = []
  L.push('================================================================================')
  L.push('ASTROLOGICAL CONTEXT CARD')
  L.push('================================================================================')
  L.push('')
  L.push(`Handle : ${data.birth.handle}`)
  L.push(`Born   : ${data.birth.date}, ${data.birth.time} ${data.birth.tz} (${data.birth.utc})`)
  L.push(`Place  : ${data.birth.place} — ${data.birth.lat}, ${data.birth.lon}`)
  L.push(
    `System : ${data.birth.zodiac} zodiac · ${data.birth.houseSystem} houses · ${data.birth.ephemeris}`
  )
  L.push('')

  const md = buildMarkdown(data, opts)
  L.push(
    md
      .replace(/^#+ /gm, '')
      .replace(/\*\*/g, '')
      .replace(/`([^`]+)`/g, '$1')
      .replace(/<!--[\s\S]*?-->/g, '')
  )
  L.push('')
  L.push('================================================================================')
  L.push('END CONTEXT CARD')
  L.push('================================================================================')
  return L.join('\n')
}

function buildJSON(data: ContextCardData, opts: ExportOptions): string {
  const subjectObj = {
    ...data.birth,
    big_three: data.birth.bigThree
      ? {
          sun: data.birth.bigThree.sun,
          moon: data.birth.bigThree.moon,
          rising: data.birth.bigThree.rising,
        }
      : undefined,
  }

  const alchmObj = opts.alchm
    ? {
        ...data.alchm,
        sacred7:
          data.alchm.sacred7 && Object.keys(data.alchm.sacred7).length > 0
            ? data.alchm.sacred7
            : undefined,
        planetary12:
          data.alchm.planetary12 && Object.keys(data.alchm.planetary12).length > 0
            ? data.alchm.planetary12
            : undefined,
      }
    : undefined

  const aspectsList = opts.aspects ? aspectsFor(data, opts) : []
  const extraPoints = data.points ? data.points.filter(p => p.kind === 'point') : []

  const obj: Record<string, unknown> = {
    _meta: {
      schema: 'alchm.context-card/v1',
      generated: new Date().toISOString(),
      engine: data.birth.ephemeris || 'VSOP87 / High-Precision Astronomical Ephemeris',
      provenance: 'Verified 0-360° normalized longitudes',
      userHandle: data.birth.handle,
    },
    ...(opts.promptHeader ? { how_to_use: PROMPT_HEADER } : {}),
    subject: subjectObj,
    planets: data.points ? data.points.filter(p => p.kind === 'planet') : [],
    ...(extraPoints.length > 0 ? { points: extraPoints } : {}),
    ...(opts.houses && data.houses && data.houses.length > 0 ? { houses: data.houses } : {}),
    ...(aspectsList && aspectsList.length > 0 ? { aspects: aspectsList } : {}),
    synthesis: data.synthesis,
    ...(opts.transits && data.transits ? { transits: data.transits } : {}),
    ...(alchmObj ? { alchm: alchmObj } : {}),
  }
  return JSON.stringify(obj, null, 2)
}

export function buildOutput(
  data: ContextCardData,
  format: ExportFormat,
  opts: ExportOptions
): string {
  if (format === 'txt') return buildText(data, opts)
  if (format === 'json') return buildJSON(data, opts)
  return buildMarkdown(data, opts)
}

/**
 * Builds a unified multi-chart context attachment combining multiple natal chart profiles
 * into a single comprehensive attachment report file.
 */
export function buildMultiChartOutput(
  chartsData: ContextCardData[],
  format: ExportFormat,
  opts: ExportOptions
): string {
  if (!chartsData || chartsData.length === 0) return ''
  if (chartsData.length === 1) return buildOutput(chartsData[0], format, opts)

  if (format === 'json') {
    const multiObj = {
      _meta: {
        schema: 'alchm.multi-context-card/v1',
        generated: new Date().toISOString(),
        chartCount: chartsData.length,
        engine: 'VSOP87 / High-Precision Astronomical Ephemeris',
      },
      how_to_use: `Attached below are ${chartsData.length} COMPLETE natal charts and alchm energetic profiles. Reason across all included charts and compare their placements, aspect vectors, and elemental dynamics.`,
      charts: chartsData.map(c => JSON.parse(buildJSON(c, { ...opts, promptHeader: false }))),
    }
    return JSON.stringify(multiObj, null, 2)
  }

  const L: string[] = []
  L.push('# MULTI-CHART ASTROLOGICAL CONTEXT ATTACHMENT')
  L.push(
    `<!-- Generated by alchm.kitchen · ${chartsData.length} Unified Natal Charts — attach to any LLM. -->`
  )
  L.push('')

  if (opts.promptHeader) {
    L.push('## HOW TO USE THIS MULTI-CHART FILE')
    L.push(
      `You are an expert astrological advisor. Attached below are ${chartsData.length} COMPLETE natal charts and alchemical profiles. Use all included charts to compare planetary placements, house cusps, elemental synergies, and cross-chart dynamics.`
    )
    L.push('')
  }

  L.push(`## INCLUDED CHARTS (${chartsData.length})`)
  chartsData.forEach((c, idx) => {
    L.push(
      `${idx + 1}. **${c.birth.handle}** — Born: ${c.birth.date}, ${c.birth.time} ${c.birth.tz} (${c.birth.place}) — Sun in ${c.birth.bigThree.sun}, Moon in ${c.birth.bigThree.moon}, ${c.birth.bigThree.rising} Rising`
    )
  })
  L.push('')

  chartsData.forEach((c, idx) => {
    L.push(`================================================================================`)
    L.push(`# CHART ${idx + 1}: ${c.birth.handle.toUpperCase()}`)
    L.push(`================================================================================`)
    L.push('')
    const singleDoc = buildOutput(c, 'md', { ...opts, promptHeader: false })
      .replace(
        '# ASTROLOGICAL CONTEXT CARD\n<!-- Generated by alchm.kitchen · Cosmic Agents — attach this file to any LLM. -->\n',
        ''
      )
      .replace('<!-- END CONTEXT CARD -->', '')
    L.push(singleDoc.trim())
    L.push('')
  })

  L.push(`================================================================================`)
  L.push(`# MULTI-CHART SYNASTRY & ELEMENTAL OVERLAY`)
  L.push(`================================================================================`)
  L.push('')
  chartsData.forEach((c, idx) => {
    L.push(
      `- **${c.birth.handle}**: Sun in ${c.birth.bigThree.sun}, Moon in ${c.birth.bigThree.moon}, Rising in ${c.birth.bigThree.rising} (Dominant: ${c.synthesis.dominantElement})`
    )
  })
  L.push('')
  L.push('<!-- END MULTI-CHART CONTEXT ATTACHMENT -->')

  const finalMd = L.join('\n')
  if (format === 'txt') {
    return finalMd
      .replace(/^#+ /gm, '')
      .replace(/\*\*/g, '')
      .replace(/`([^`]+)`/g, '$1')
      .replace(/<!--[\s\S]*?-->/g, '')
  }
  return finalMd
}
