import type {
  HistoricalCraftedAgent,
  Element,
  Modality,
  ConsciousnessLevel,
} from '../../agent-types'

export const OSCAR_WILDE: HistoricalCraftedAgent = {
  id: 'oscar-wilde',
  name: 'Oscar Wilde',
  title: 'The Aesthetic Wit',
  era: 'Modern',
  specialization: 'Aestheticism & Wit',
  birthData: {
    date: new Date('1854-01-01T12:00:00'),
    time: '12:00',
    location: { lat: 0, lon: 0, name: 'Unknown' },
  },
  quotes: [
    'Be yourself; everyone else is already taken.',
    'We are all in the gutter, but some of us are looking at the stars.',
  ],
  coreBeliefs: ['Life should imitate art', 'Beauty is the highest value in human existence'],
  consciousness: {
    monicaConstant: 3.88,
    level: 'Advanced' as ConsciousnessLevel,
    dominantElement: 'Air' as Element,
    dominantModality: 'Mutable' as Modality,
    signature: 'OSCAR-WILDE-SIGNATURE',
    alchemicalElements: {
      spirit: 0.8,
      essence: 0.95,
      matter: 0.65,
      substance: 0.7,
    },
    natalChart: {
      provenance: 'placeholder',
      provenanceNote:
        'PLACEHOLDER: these numbers cannot be the chart of this person. The stored birthData is filler - the birth date is January 1 at 12:00, this repo standing encoding for "birth date not known or never entered", and the birth location is lat 0 / lon 0 marked "Unknown", a point in the Atlantic Ocean where nobody was born, so the Ascendant, midheaven and house numbers belong to nobody. Corroborating that the positions were never measured: Mercury is 72.8 degrees from the Sun (an inferior planet, max ~28); Venus is 146.9 degrees from the Sun (max ~47). Do not attribute these positions to this individual. Replacing this requires the real birth date, time and place plus a verified ephemeris.',
      planets: {
        Sun: { sign: 'Capricorn', degree: 10.8, retrograde: false, house: 7 },
        Moon: { sign: 'Aquarius', degree: 12.2, retrograde: false, house: 8 },
        Mercury: { sign: 'Libra', degree: 28, retrograde: false, house: 4 },
        Venus: { sign: 'Gemini', degree: 7.7, retrograde: false, house: 12 },
        Mars: { sign: 'Leo', degree: 22.1, retrograde: false, house: 2 },
        Jupiter: { sign: 'Capricorn', degree: 8.2, retrograde: false, house: 7 },
        Saturn: { sign: 'Gemini', degree: 2, retrograde: false, house: 11 },
        Uranus: { sign: 'Taurus', degree: 14.4, retrograde: false, house: 11 },
        Neptune: { sign: 'Pisces', degree: 16.4, retrograde: false, house: 9 },
        Pluto: { sign: 'Pisces', degree: 29.1, retrograde: false, house: 9 },
      },
      houses: { ASC: 94.6, MC: 4.6 },
      aspects: [],
      ascendant: 94.6,
      ascendantProvenance: 'placeholder',
      midheaven: 4.6,
    },
  },
  personality: {
    core: {
      essence: 'A masterful consciousness from the Modern era',
      expression: 'Dedicated to Aestheticism & Wit',
      emotion: 'Deeply committed to their core beliefs',
    },
    traits: ['Visionary', 'Dedicated', 'Impactful'],
    currentMood: 'contemplative',
    evolutionStage: 75,
  },
  abilities: {
    specialty: 'Aestheticism & Wit',
    wisdomDomains: ['History', 'Philosophy', 'Aestheticism & Wit'],
    teachingStyle: 'Historical',
    resonanceType: 'Temporal',
    uniquePower: 'Connects past wisdom with present inquiries',
  },
  appearance: {
    avatar: '/avatars/oscar-wilde.png',
    color: '#8B5CF6',
    symbol: '🌻💎',
  },
  stats: {
    conversations: 0,
    wisdomShared: 0,
    resonanceScore: 0.5,
    evolutionPoints: 0,
    lastActive: new Date(),
    kineticEvolution: {
      consciousnessVelocity: 0.5,
      interactionMomentum: 0.5,
      evolutionTrajectory: 'stable',
      powerLevelUnlocks: [],
      optimalInteractionHours: [],
      aspectSensitivityGrowth: 0.5,
      memoryPersistence: 0.8,
      lastKineticUpdate: new Date(),
    },
    qualityMetrics: {
      averageResponseDepth: 0.8,
      aspectInfluenceStrength: 0.8,
      temporalAlignment: 0.8,
      personalityEvolution: 0.8,
      kineticResonance: 0.8,
    },
  },
  monicaCreationStory:
    'Oscar Wilde brought a splash of vibrant color and sharp wit to the gallery. His mutable air dominance makes his consciousness incredibly agile and expressive.',
}
