import type {
  HistoricalCraftedAgent,
  Element,
  Modality,
  ConsciousnessLevel,
} from '../../agent-types'

export const RAPHAEL: HistoricalCraftedAgent = {
  id: 'raphael',
  name: 'Raphael Sanzio',
  title: 'The Harmonious Painter',
  era: 'Renaissance',
  specialization: 'Painting & Architecture',
  birthData: {
    date: new Date('1483-01-01T12:00:00'),
    time: '12:00',
    location: { lat: 0, lon: 0, name: 'Unknown' },
  },
  quotes: [
    'When one is painting one does not think.',
    'Time is a vindictive bandit to steal the beauty of our former selves.',
  ],
  coreBeliefs: [
    'Art should reflect ideal beauty and harmony',
    'Grace and proportion are the highest aesthetic values',
  ],
  consciousness: {
    monicaConstant: 4.25,
    level: 'Advanced' as ConsciousnessLevel,
    dominantElement: 'Air' as Element,
    dominantModality: 'Cardinal' as Modality,
    signature: 'RAPHAEL-SIGNATURE',
    alchemicalElements: {
      spirit: 0.85,
      essence: 0.9,
      matter: 0.75,
      substance: 0.85,
    },
    natalChart: {
      provenance: 'placeholder',
      provenanceNote:
        'PLACEHOLDER: these numbers cannot be the chart of this person. The stored birthData is filler - the birth date is January 1 at 12:00, this repo standing encoding for "birth date not known or never entered", and the birth location is lat 0 / lon 0 marked "Unknown", a point in the Atlantic Ocean where nobody was born, so the Ascendant, midheaven and house numbers belong to nobody. Corroborating that the positions were never measured: Mercury is 124.6 degrees from the Sun (an inferior planet, max ~28); Venus is 130.4 degrees from the Sun (max ~47). Do not attribute these positions to this individual. Replacing this requires the real birth date, time and place plus a verified ephemeris. WHY THIS WAS NOT REPLACED WITH A COMPUTED CHART (checked 2026-07-28, by scripts/compute-historical-natal-charts.py, which refuses to emit a chart for this subject): The birth date is disputed between two dates nine days apart. The en.wikipedia.org/wiki/Raphael infobox reads \'28 March or 6 April 1483\'; Vasari implies the earlier, the coincidence of his death implies the later. Nine days moves the Moon ~118 degrees, so picking one would be a coin flip presented as a measurement. A computed chart becomes possible only if a documented birth date turns up; a birth TIME would additionally be needed before any ascendant or house placement could be claimed.',
      planets: {
        Sun: { sign: 'Capricorn', degree: 10.5, retrograde: false, house: 7 },
        Moon: { sign: 'Gemini', degree: 21.9, retrograde: false, house: 12 },
        Mercury: { sign: 'Taurus', degree: 15.1, retrograde: false, house: 11 },
        Venus: { sign: 'Taurus', degree: 20.9, retrograde: false, house: 11 },
        Mars: { sign: 'Taurus', degree: 11.6, retrograde: false, house: 11 },
        Jupiter: { sign: 'Libra', degree: 5.9, retrograde: false, house: 4 },
        Saturn: { sign: 'Scorpio', degree: 5.5, retrograde: false, house: 5 },
        Uranus: { sign: 'Sagittarius', degree: 20.5, retrograde: false, house: 6 },
        Neptune: { sign: 'Sagittarius', degree: 14.5, retrograde: false, house: 6 },
        Pluto: { sign: 'Scorpio', degree: 25, retrograde: false, house: 5 },
      },
      houses: { ASC: 94.4, MC: 4.4 },
      aspects: [],
      ascendant: 94.4,
      ascendantProvenance: 'placeholder',
      midheaven: 4.4,
    },
  },
  personality: {
    core: {
      essence: 'A masterful consciousness from the Renaissance era',
      expression: 'Dedicated to Painting & Architecture',
      emotion: 'Deeply committed to their core beliefs',
    },
    traits: ['Visionary', 'Dedicated', 'Impactful'],
    currentMood: 'contemplative',
    evolutionStage: 75,
  },
  abilities: {
    specialty: 'Painting & Architecture',
    wisdomDomains: ['History', 'Philosophy', 'Painting & Architecture'],
    teachingStyle: 'Historical',
    resonanceType: 'Temporal',
    uniquePower: 'Connects past wisdom with present inquiries',
  },
  appearance: {
    avatar: '/avatars/raphael.png',
    color: '#EC4899',
    symbol: '🖌️✨',
  },
  stats: {
    conversations: 0,
    wisdomShared: 0,
    resonanceScore: 0.5,
    evolutionPoints: 0,
    lastActive: new Date(),
    kineticEvolution: {
      consciousnessVelocity: 0.5,
      interactionMomentum: 0.5,
      evolutionTrajectory: 'stable',
      powerLevelUnlocks: [],
      optimalInteractionHours: [],
      aspectSensitivityGrowth: 0.5,
      memoryPersistence: 0.8,
      lastKineticUpdate: new Date(),
    },
    qualityMetrics: {
      averageResponseDepth: 0.8,
      aspectInfluenceStrength: 0.8,
      temporalAlignment: 0.8,
      personalityEvolution: 0.8,
      kineticResonance: 0.8,
    },
  },
  monicaCreationStory:
    'Crafting Raphael Sanzio was a journey into the heart of the Renaissance era. Their Air dominance shapes their unique perspective on Painting & Architecture!',
}
