//! Golden-value tests: assert the Rust math reproduces the AUTHORITATIVE Python
//! implementation. `fixtures/golden.json` was generated by
//! `fixtures/golden_gen.py` (which imports the real `backend/utils.py`).
//!
//! Regenerate with:
//!   backend/venv/bin/python pa-rust-backend/tests/fixtures/golden_gen.py

use chrono::{NaiveDate, NaiveDateTime};
use pa_rust_backend::astro::alchemy::{
    aggregate_alchemical_properties, alchemize, alchemize_detailed, ensure_from_positions,
    get_planetary_modifiers, normalize_alchm_weight, normalize_planet_weight,
};
use pa_rust_backend::astro::aspects::{calculate_aspect_efficiency, calculate_aspects};
use pa_rust_backend::astro::consciousness::{calculate_monica_constant, get_consciousness_level};
use pa_rust_backend::astro::kinetics::calculate_kinetics;
use pa_rust_backend::astro::positions::{elemental_scores, planetary_positions_for};
use serde_json::Value;

const GOLDEN: &str = include_str!("fixtures/golden.json");

fn golden() -> Value {
    serde_json::from_str(GOLDEN).expect("golden.json parses")
}

fn dt() -> NaiveDateTime {
    NaiveDate::from_ymd_opt(2026, 6, 8)
        .unwrap()
        .and_hms_opt(14, 30, 0)
        .unwrap()
}

/// Lenient float comparison: real bugs differ by orders of magnitude, while
/// float reassociation never exceeds this band.
fn approx(a: f64, b: f64) -> bool {
    (a - b).abs() <= 1e-6 + 1e-6 * b.abs()
}

fn assert_close(label: &str, got: f64, want: f64) {
    assert!(
        approx(got, want),
        "{label}: got {got}, want {want} (delta {})",
        (got - want).abs()
    );
}

#[test]
fn positions_match_python() {
    let g = golden();
    let want = &g["positions"];
    let got = planetary_positions_for(dt());

    for planet in [
        "Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune",
        "Pluto",
    ] {
        let w = &want[planet];
        let p = got
            .get(planet)
            .unwrap_or_else(|| panic!("missing {planet}"));
        assert_eq!(p.sign, w["sign"].as_str().unwrap(), "{planet} sign");
        assert_eq!(p.degree, w["degree"].as_i64().unwrap(), "{planet} degree");
        assert_eq!(p.minute, w["minute"].as_i64().unwrap(), "{planet} minute");
        assert_close(
            &format!("{planet} exactLongitude"),
            p.exact_longitude,
            w["exactLongitude"].as_f64().unwrap(),
        );
        assert_close(
            &format!("{planet} longitudeSpeed"),
            p.longitude_speed,
            w["longitudeSpeed"].as_f64().unwrap(),
        );
        assert_close(
            &format!("{planet} arcminutesPerDay"),
            p.arcminutes_per_day,
            w["arcminutesPerDay"].as_f64().unwrap(),
        );
    }
}

#[test]
fn alchemize_matches_python() {
    let g = golden();
    let w = &g["alchemize"];

    let current = ensure_from_positions(&planetary_positions_for(dt()));
    let prev = ensure_from_positions(&planetary_positions_for(dt() - chrono::Duration::days(1)));
    let r = alchemize(&current, Some(&prev), dt());

    assert_close(
        "Spirit",
        r.esms.spirit,
        w["esms"]["Spirit"].as_f64().unwrap(),
    );
    assert_close(
        "Essence",
        r.esms.essence,
        w["esms"]["Essence"].as_f64().unwrap(),
    );
    assert_close(
        "Matter",
        r.esms.matter,
        w["esms"]["Matter"].as_f64().unwrap(),
    );
    assert_close(
        "Substance",
        r.esms.substance,
        w["esms"]["Substance"].as_f64().unwrap(),
    );

    let tp = &w["thermodynamicProperties"];
    assert_close(
        "heat",
        r.thermodynamic_properties.heat,
        tp["heat"].as_f64().unwrap(),
    );
    assert_close(
        "entropy",
        r.thermodynamic_properties.entropy,
        tp["entropy"].as_f64().unwrap(),
    );
    assert_close(
        "reactivity",
        r.thermodynamic_properties.reactivity,
        tp["reactivity"].as_f64().unwrap(),
    );
    assert_close(
        "gregsEnergy",
        r.thermodynamic_properties.gregs_energy,
        tp["gregsEnergy"].as_f64().unwrap(),
    );

    assert_close("kalchm", r.kalchm, w["kalchm"].as_f64().unwrap());
    assert_close("monica", r.monica, w["monica"].as_f64().unwrap());
    assert_close("score", r.score, w["score"].as_f64().unwrap());

    let ep = &w["elementalProperties"];
    assert_close(
        "Fire",
        r.elemental_properties.fire,
        ep["Fire"].as_f64().unwrap(),
    );
    assert_close(
        "Water",
        r.elemental_properties.water,
        ep["Water"].as_f64().unwrap(),
    );
    assert_close(
        "Earth",
        r.elemental_properties.earth,
        ep["Earth"].as_f64().unwrap(),
    );
    assert_close(
        "Air",
        r.elemental_properties.air,
        ep["Air"].as_f64().unwrap(),
    );

    assert_eq!(
        r.metadata.dominant_element,
        w["metadata"]["dominantElement"].as_str().unwrap()
    );
    assert_eq!(
        r.metadata.sun_sign,
        w["metadata"]["sunSign"].as_str().unwrap()
    );
    assert_eq!(
        r.metadata.chart_ruler,
        w["metadata"]["chartRuler"].as_str().unwrap()
    );
    assert_eq!(
        r.metadata.is_diurnal,
        w["metadata"]["isDiurnal"].as_bool().unwrap()
    );

    // Per-planet momentum.
    for (planet, val) in w["planetaryMomentum"].as_object().unwrap() {
        let got = *r.planetary_momentum.get(planet).unwrap();
        assert_close(&format!("momentum {planet}"), got, val.as_f64().unwrap());
    }
}

#[test]
fn alchemize_detailed_has_per_planet() {
    let g = golden();
    let w = &g["alchemize_detailed"]["perPlanet"];
    let current = ensure_from_positions(&planetary_positions_for(dt()));
    let prev = ensure_from_positions(&planetary_positions_for(dt() - chrono::Duration::days(1)));
    let r = alchemize_detailed(&current, Some(&prev), dt());
    let pp = r.per_planet.expect("perPlanet present");
    let wsun = &w["Sun"];
    let sun = pp.get("Sun").unwrap();
    assert_close(
        "Sun esms Spirit",
        sun.esms.spirit,
        wsun["esms"]["Spirit"].as_f64().unwrap(),
    );
    assert_close(
        "Sun alchmWeight",
        sun.alchm_weight,
        wsun["alchmWeight"].as_f64().unwrap(),
    );
    assert_eq!(sun.sign_element, wsun["signElement"].as_str().unwrap());
}

#[test]
fn aspects_match_python() {
    let g = golden();
    let want = g["aspects"]["aspects"].as_array().unwrap();
    let current = ensure_from_positions(&planetary_positions_for(dt()));
    let got = calculate_aspects(&current);

    assert_eq!(got.len(), want.len(), "aspect count");
    for (i, w) in want.iter().enumerate() {
        let a = &got[i];
        assert_eq!(
            a.planet1,
            w["planet1"].as_str().unwrap(),
            "aspect {i} planet1"
        );
        assert_eq!(
            a.planet2,
            w["planet2"].as_str().unwrap(),
            "aspect {i} planet2"
        );
        assert_eq!(
            a.aspect_type,
            w["type"].as_str().unwrap(),
            "aspect {i} type"
        );
        assert_close(
            &format!("aspect {i} orb"),
            a.orb,
            w["orb"].as_f64().unwrap(),
        );
        assert_close(
            &format!("aspect {i} strength"),
            a.strength,
            w["strength"].as_f64().unwrap(),
        );
    }

    assert_close(
        "aspect_efficiency",
        calculate_aspect_efficiency(&current),
        g["aspect_efficiency"].as_f64().unwrap(),
    );
}

#[test]
fn aggregate_and_modifiers_match() {
    let g = golden();
    let current = ensure_from_positions(&planetary_positions_for(dt()));
    let t = aggregate_alchemical_properties(&current);
    let w = &g["aggregate"];
    assert_close("agg Spirit", t.spirit, w["Spirit"].as_f64().unwrap());
    assert_close("agg Essence", t.essence, w["Essence"].as_f64().unwrap());
    assert_close("agg Matter", t.matter, w["Matter"].as_f64().unwrap());
    assert_close(
        "agg Substance",
        t.substance,
        w["Substance"].as_f64().unwrap(),
    );
    assert_close("agg Fire", t.fire, w["Fire"].as_f64().unwrap());
    assert_close("agg Water", t.water, w["Water"].as_f64().unwrap());
    assert_close("agg Air", t.air, w["Air"].as_f64().unwrap());
    assert_close("agg Earth", t.earth, w["Earth"].as_f64().unwrap());

    let m = get_planetary_modifiers("Sun");
    let wm = &g["modifiers_sun"];
    assert_close("mod velocity", m.velocity, wm["velocity"].as_f64().unwrap());
    assert_close("mod inertia", m.inertia, wm["inertia"].as_f64().unwrap());
    assert_close("mod current", m.current, wm["current"].as_f64().unwrap());
    assert_close("mod force", m.force, wm["force"].as_f64().unwrap());

    assert_close(
        "normalize_alchm_weight(1.0)",
        normalize_alchm_weight(1.0),
        g["normalize_alchm_weight_sun"].as_f64().unwrap(),
    );
    assert_close(
        "normalize_planet_weight(333000)",
        normalize_planet_weight(333000.0),
        g["normalize_planet_weight_sun"].as_f64().unwrap(),
    );
}

#[test]
fn elemental_scores_match() {
    let g = golden();
    let s = elemental_scores(dt());
    let w = &g["elemental_scores"];
    for key in [
        "spirit_score",
        "essence_score",
        "matter_score",
        "substance_score",
    ] {
        assert_close(key, *s.get(key).unwrap(), w[key].as_f64().unwrap());
    }
}

#[test]
fn kinetics_match_python() {
    let g = golden();
    let w = &g["kinetics"];
    let current = ensure_from_positions(&planetary_positions_for(dt()));
    let prev = ensure_from_positions(&planetary_positions_for(dt() - chrono::Duration::days(1)));
    let k = calculate_kinetics(&current, Some(&prev), 3600.0, "Sun", None, dt());

    assert_close("charge", k.charge, w["charge"].as_f64().unwrap());
    assert_close(
        "forceMagnitude",
        k.force_magnitude,
        w["forceMagnitude"].as_f64().unwrap(),
    );
    assert_close("inertia", k.inertia, w["inertia"].as_f64().unwrap());
    assert_close(
        "potentialDifference",
        k.potential_difference,
        w["potentialDifference"].as_f64().unwrap(),
    );
    assert_close(
        "velocity.Fire",
        k.velocity.fire,
        w["velocity"]["Fire"].as_f64().unwrap(),
    );
    assert_close(
        "velocity.Water",
        k.velocity.water,
        w["velocity"]["Water"].as_f64().unwrap(),
    );
    assert_eq!(k.thermal_direction, w["thermalDirection"].as_str().unwrap());
    assert_eq!(
        k.force_classification,
        w["forceClassification"].as_str().unwrap()
    );
    assert_eq!(
        k.aspect_phase.as_ref().unwrap().phase_type,
        w["aspectPhase"]["type"].as_str().unwrap()
    );
}

#[test]
fn monica_and_consciousness_match() {
    let g = golden();
    let ms = &g["monica_constant_samples"];
    assert_close(
        "monica(1,2,3,4)",
        calculate_monica_constant(1.0, 2.0, 3.0, 4.0),
        ms["1_2_3_4"].as_f64().unwrap(),
    );
    assert_close(
        "monica(0,0,0,0)",
        calculate_monica_constant(0.0, 0.0, 0.0, 0.0),
        ms["0_0_0_0"].as_f64().unwrap(),
    );

    for (level_str, want) in g["consciousness_levels"].as_object().unwrap() {
        let v: f64 = level_str.parse().unwrap();
        assert_eq!(
            get_consciousness_level(v),
            want.as_str().unwrap(),
            "consciousness level for {v}"
        );
    }
}
