import { PlanetData } from './types'

const jupiterData: PlanetData = {
  'Dignity Effect': {
    Pisces: 1,
    Sagittarius: 1,
    Cancer: 2,
    Gemini: -1,
    Virgo: -1,
    Capricorn: -2,
  },
  Elements: ['Air', 'Fire'],
  Alchemy: {
    Spirit: 1,
    Essence: 1,
    Matter: 0,
    Substance: 0,
  },
  'Diurnal Element': 'Air',
  'Nocturnal Element': 'Fire',
  AstronomicalData: {
    DistanceFromSun: '484 million miles (778 million kilometers)',
    DistanceFromEarth: {
      Minimum: '365 million miles (588 million kilometers)',
      Maximum: '601 million miles (968 million kilometers)',
    },
    Diameter: '86,881 miles (139,820 kilometers)',
    SurfaceTemperature: '-234 degrees Fahrenheit (-145 Celsius) cloud tops',
    AtmosphericComposition:
      'Primarily hydrogen and helium with traces of methane, ammonia, and water',
    RotationPeriod: '9.93 Earth hours',
    OrbitPeriod: '11.86 Earth years',
    'Axial Tilt': '3.13 degrees',
    PhaseCycle: '399 days (synodic period)',
    SunlightTravelTime: '43 minutes',
    PhysicalCharacteristics: {
      Surface:
        'Gas giant with no solid surface, characterized by colorful bands and the Great Red Spot',
      MagneticField: 'Strongest magnetic field of any planet in the solar system',
      Composition: 'Mostly hydrogen and helium, possibly with a rocky core',
      NotableFeatures:
        'Largest planet in our solar system, 79 known moons, visible rings, Great Red Spot (giant storm)',
    },
  },
  AstrologicalProperties: {
    AlchemicalName: 'Zeus',
    BeneficType: 'Greater benefic',
    DualDomicile: {
      Winter: 'Pisces (yin)',
      Summer: 'Sagittarius (yang)',
    },
    HouseJoy: 9,
    CyclePeriod: {
      Return: '12 years',
      Retrograde: '4 months yearly',
    },
    Exaltation: 'Cancer',
    Fall: 'Capricorn',
    Detriment: ['Gemini', 'Virgo'],
    Keywords: [
      'Expansion',
      'Growth',
      'Abundance',
      'Luck',
      'Optimism',
      'Wisdom',
      'Philosophy',
      'Teaching',
      'Travel',
    ],
    Colors: ['Royal Purple', 'Deep Blue', 'Indigo', 'Gold', 'Yellow', 'Royal Blue'],
    Day: 'Thursday',
    Metal: 'Tin',
    BodyParts: ['Liver', 'Thighs', 'Hips', 'Blood', 'Fat tissues', 'Growth mechanisms'],
    Animals: ['Eagle', 'Elephant', 'Deer', 'Horse', 'Dolphin'],
    Stones: ['Sapphire', 'Lapis Lazuli', 'Amethyst', 'Turquoise', 'Blue Topaz'],
  },
  ElementalConnections: {
    DayEmission: 'Spirit - "that which animates"',
    NightEmission: 'Essence - "that which an object cannot exist without"',
    ElementalBridges: ['Connects Air and Fire', 'Bridges intellect and passion'],
    SharedElements: {
      Air: ['Mercury', 'Saturn'],
      Fire: ['Mars', 'Sun'],
    },
    AssociatedQualities: [
      'Expansive',
      'Warm',
      'Moist',
      'Abundant',
      'Generous',
      'Optimistic',
      'Educational',
      'Philosophical',
      'Benevolent',
      'Growth-oriented',
    ],
  },
  HerbalAssociations: {
    Herbs: [
      'Sage',
      'Dandelion',
      'Borage',
      'Hyssop',
      'Melissa',
      'Mint',
      'Nutmeg',
      'Cinnamon',
      'Clove',
      'Anise',
      'Ginger',
      'Basil',
      'Rosemary',
      'Bay Leaf',
      'Chicory',
      'Fenugreek',
      'Licorice Root',
      'Burdock',
    ],
    Flowers: [
      'Dandelion',
      'Honeysuckle',
      'Violet',
      'Carnation',
      'Purple Hyacinth',
      'Forget-me-nots',
      'Blue Flag',
      'Clematis',
      'Purple Amaranth',
      'Blue Salvia',
    ],
    Woods: ['Oak', 'Pine', 'Cedar', 'Fig', 'Ash'],
    Scents: [
      'Frankincense',
      'Nutmeg',
      'Cinnamon',
      'Sage',
      'Cedar',
      'Bergamot',
      'Clove',
      'Sandalwood',
      'Benzoin',
      'Vanilla',
    ],
  },
  FoodAssociations: [
    'rich and abundant foods',
    'exotic spices',
    'saffron',
    'nutmeg',
    'cinnamon',
    'large fruits',
    'hearty grains',
    'liver',
    'truffle',
    'aged cheeses',
    'wine and spirits',
    'feast foods',
    'international cuisines',
    'generous portions',
    'celebratory dishes',
    'luxurious ingredients',
    'ethnic delicacies',
    'honey',
    'maple syrup',
    'figs',
    'dates',
    'tropical fruits',
    'rich desserts',
    'multi-course meals',
    'lavish banquet foods',
    'wholesome breads',
    'holiday foods',
  ],
  FlavorProfiles: {
    Sweet: 0.7,
    Sour: 0.2,
    Salty: 0.4,
    Bitter: 0.2,
    Umami: 0.7,
    Spicy: 0.5,
  },
  CulinaryInfluences: [
    'Expands and enhances flavors',
    'Improves fermentation and aging processes',
    'Supports traditional cooking methods',
    'Balances complex flavor profiles',
    'Increases perception of richness and depth',
    'Encourages culinary exploration and travel',
    'Supports generous hospitality',
    'Enhances multicultural fusion',
    'Promotes abundance and prosperity',
    'Facilitates celebratory and festive meals',
    'Encourages educational cooking experiences',
    'Inspires culinary wisdom and tradition',
  ],
  AspectsEffect: {
    Sun: {
      Conjunction: 0.8,
      Opposition: 0.4,
      Trine: 0.6,
      Square: 0.2,
      Sextile: 0.5,
    },
    Moon: {
      Conjunction: 0.7,
      Opposition: 0.3,
      Trine: 0.6,
      Square: 0.2,
      Sextile: 0.4,
    },
    Mercury: {
      Conjunction: 0.5,
      Opposition: 0.1,
      Trine: 0.4,
      Square: 0.0,
      Sextile: 0.3,
    },
    Saturn: {
      Conjunction: 0.3,
      Opposition: -0.2,
      Trine: 0.4,
      Square: -0.1,
      Sextile: 0.2,
    },
    Venus: {
      Conjunction: 0.8,
      Opposition: 0.3,
      Trine: 0.6,
      Square: 0.2,
      Sextile: 0.5,
    },
    Mars: {
      Conjunction: 0.6,
      Opposition: 0.1,
      Trine: 0.5,
      Square: 0.0,
      Sextile: 0.3,
    },
  },
  PlanetSpecific: {
    ZodiacTransit: {
      Sagittarius: {
        FoodFocus: 'Abundant, celebratory dishes with exotic spices and foreign influences',
        Elements: {
          Fire: 0.8,
          Earth: 0.2,
          Air: 0.4,
          Water: 0.2,
        },
        Ingredients: [
          'international spices',
          'game meats',
          'exotic fruits',
          'hearty stews',
          'celebratory dishes',
          'festive breads',
        ],
      },
      Pisces: {
        FoodFocus: 'Spiritual and healing foods, seafood, and dishes with subtle, complex flavors',
        Elements: {
          Fire: 0.2,
          Earth: 0.1,
          Air: 0.2,
          Water: 0.9,
        },
        Ingredients: [
          'seafood',
          'healing herbs',
          'infused oils',
          'mead',
          'fermented foods',
          'sacred recipes',
        ],
      },
      Aries: {
        FoodFocus:
          'Bold, pioneering fusion dishes with adventurous flavors and innovative techniques',
        Elements: {
          Fire: 0.9,
          Earth: 0.1,
          Air: 0.4,
          Water: 0.1,
        },
        Ingredients: [
          'chili peppers',
          'global spice blends',
          'large roasted meats',
          'abundant platters',
          'adventurous combinations',
        ],
      },
      Taurus: {
        FoodFocus: 'Rich, indulgent comfort foods with emphasis on quality and luxury ingredients',
        Elements: {
          Fire: 0.3,
          Earth: 0.8,
          Air: 0.1,
          Water: 0.2,
        },
        Ingredients: [
          'truffles',
          'aged cheeses',
          'fine chocolate',
          'rich desserts',
          'quality meats',
          'decadent sauces',
        ],
      },
    },
    Retrograde: {
      CulinaryEffect:
        'Reevaluation of rich dishes, moderation in abundance, return to simpler preparations',
      ElementalShift: {
        Spirit: 0.8,
        Essence: 0.6,
        Matter: 0.2,
        Substance: 0.1,
      },
    },
    CulinaryTemperament: {
      FireJupiter: {
        FoodFocus:
          'Bold, expansive flavors with emphasis on global traditions and fire cooking methods',
        Elements: {
          Fire: 0.9,
          Earth: 0.3,
          Air: 0.4,
          Water: 0.2,
        },
        Recommendations: [
          'feast-style service',
          'multicultural fusion',
          'generous portions',
          'celebratory ingredients',
          'culinary education',
        ],
      },
      AirJupiter: {
        FoodFocus:
          'Intellectual approaches to cuisine with emphasis on philosophy and global knowledge',
        Elements: {
          Fire: 0.3,
          Earth: 0.2,
          Air: 0.9,
          Water: 0.3,
        },
        Recommendations: [
          'cuisine theory',
          'innovative presentations',
          'culinary storytelling',
          'educational dining',
          'historical influences',
        ],
      },
    },
    CulinaryTechniques: {
      Abundance: 0.9,
      'Cultural Fusion': 0.8,
      'Educational Dining': 0.7,
      'Festive Preparation': 0.9,
      'Generous Hospitality': 0.9,
    },
    TransitDates: {
      Gemini: { Start: '2024-05-25', End: '2025-06-09' },
      Cancer: { Start: '2025-06-09', End: '2026-07-14' },
      Leo: { Start: '2026-07-14', End: '2027-08-10' },
      Virgo: { Start: '2027-08-10', End: '2028-09-18' },
      Libra: { Start: '2028-09-18', End: '2029-10-29' },
      Scorpio: { Start: '2029-10-29', End: '2030-11-08' },
      Sagittarius: { Start: '2030-11-08', End: '2031-12-14' },
      Capricorn: { Start: '2031-12-14', End: '2033-01-02' },
      Aquarius: { Start: '2033-01-02', End: '2034-01-19' },
      Pisces: { Start: '2034-01-19', End: '2035-02-14' },
      Aries: { Start: '2035-02-14', End: '2036-03-25' },
      Taurus: { Start: '2036-03-25', End: '2037-04-12' },
    },
  },
}

export default jupiterData
