import { PlanetData } from './types'

const saturnData: PlanetData = {
  'Dignity Effect': {
    Aquarius: 1,
    Capricorn: 1,
    Libra: 2,
    Cancer: -1,
    Leo: -1,
    Aries: -2,
  },
  Elements: ['Air', 'Earth'],
  Alchemy: {
    Spirit: 1,
    Essence: 0,
    Matter: 1,
    Substance: 0,
  },
  'Diurnal Element': 'Air',
  'Nocturnal Element': 'Earth',
  AstronomicalData: {
    DistanceFromSun: '886 million miles (1.4 billion kilometers)',
    DistanceFromEarth: {
      Minimum: '746 million miles (1.2 billion kilometers)',
      Maximum: '1 billion miles (1.7 billion kilometers)',
    },
    Diameter: '72,400 miles (116,500 kilometers)',
    SurfaceTemperature: '-288 degrees Fahrenheit (-178 Celsius)',
    AtmosphericComposition:
      'Primarily hydrogen and helium with traces of ammonia, methane, and water ice',
    RotationPeriod: '10.7 Earth hours',
    OrbitPeriod: '29.5 Earth years',
    'Axial Tilt': '26.7 degrees',
    PhaseCycle: '378 days (synodic period)',
    SunlightTravelTime: '80 minutes',
    PhysicalCharacteristics: {
      Surface: 'Gas giant with no solid surface, characterized by subtle bands and periodic storms',
      MagneticField: "Strong magnetic field, about 578 times Earth's strength",
      Composition: 'Mostly hydrogen and helium with a rocky core',
      NotableFeatures:
        'Most prominent ring system in solar system, at least 82 moons, hexagonal storm at north pole',
    },
  },
  AstrologicalProperties: {
    AlchemicalName: 'Chronos',
    MaleficType: 'Greater malefic',
    DualDomicile: {
      Summer: 'Aquarius (yang)',
      Winter: 'Capricorn (yin)',
    },
    HouseJoy: 12,
    CyclePeriod: {
      Return: '29.5 years',
      Retrograde: '4.5 months yearly',
    },
    Exaltation: 'Libra',
    Fall: 'Aries',
    Detriment: ['Cancer', 'Leo'],
    Keywords: [
      'Structure',
      'Time',
      'Discipline',
      'Restriction',
      'Maturity',
      'Responsibility',
      'Authority',
      'Endurance',
      'Patience',
    ],
    Colors: ['Black', 'Dark Brown', 'Dark Blue', 'Gray', 'Deep Purple', 'Dark Green'],
    Day: 'Saturday',
    Metal: 'Lead',
    BodyParts: ['Bones', 'Teeth', 'Skin', 'Joints', 'Gallbladder', 'Spleen', 'Knees'],
    Animals: ['Crow', 'Raven', 'Owl', 'Goat', 'Bat', 'Elephant'],
    Stones: ['Onyx', 'Obsidian', 'Jet', 'Black Tourmaline', 'Hematite', 'Smoky Quartz'],
  },
  ElementalConnections: {
    DayEmission: 'Spirit - "that which animates"',
    NightEmission: 'Matter - "that which is minimally reactive"',
    ElementalBridges: [
      'Connects Air and Earth',
      'Bridges theory and practice',
      'Links thought and form',
    ],
    SharedElements: {
      Air: ['Mercury', 'Jupiter'],
      Earth: ['Mercury', 'Venus'],
    },
    AssociatedQualities: [
      'Dry',
      'Cold',
      'Heavy',
      'Dense',
      'Restrictive',
      'Crystallizing',
      'Binding',
      'Structuring',
      'Concentrating',
      'Contracting',
    ],
  },
  HerbalAssociations: {
    Herbs: [
      'Comfrey',
      "Solomon's Seal",
      'Mullein',
      'Horsetail',
      'Skullcap',
      "Shepherd's Purse",
      'Knotweed',
      'Hemlock',
      'Mandrake',
      'Black Hellebore',
      'Asafoetida',
      'Elm',
      'Belladonna',
      'Valerian',
      'Slippery Elm',
      'Barley',
      'Fumitory',
      'Bistort',
    ],
    Flowers: [
      'Pansy',
      'Black Poppy',
      'Dark Iris',
      'Nightshade',
      'Cypress',
      'Amaranth',
      'Bryony',
      'Black Orchid',
      'Dark Tulip',
      'Winter Blooms',
    ],
    Woods: ['Cypress', 'Yew', 'Oak', 'Pine', 'Elm'],
    Scents: [
      'Cypress',
      'Patchouli',
      'Myrrh',
      'Vetiver',
      'Musk',
      'Cedar',
      'Pine',
      'Black Pepper',
      'Camphor',
      'Earthy Scents',
    ],
  },
  FoodAssociations: [
    'root vegetables',
    'aged foods',
    'preserved foods',
    'dark foods',
    'bitter greens',
    'bone broth',
    'grains',
    'seeds',
    'black foods',
    'pickled foods',
    'dried foods',
    'fermented foods',
    'foods requiring time to prepare',
    'traditional recipes',
    'old-world ingredients',
    'dark leafy greens',
    'aged cheeses',
    'cured meats',
    'legumes',
    'hearty stews',
    'beets',
    'black rice',
    'buckwheat',
    'rye',
    'dense breads',
    'salt-cured foods',
    'black sesame',
    'mushrooms',
    'black beans',
    'aged wine',
  ],
  FlavorProfiles: {
    Sweet: 0.1,
    Sour: 0.5,
    Salty: 0.3,
    Bitter: 0.9,
    Umami: 0.5,
    Spicy: 0.2,
  },
  CulinaryInfluences: [
    'Preserves and ages foods',
    'Concentrates flavors',
    'Supports slow cooking methods',
    'Enhances minerality and earthiness',
    'Improves storage and longevity',
    'Provides structure to recipes',
    'Deepens complexity through time',
    'Creates discipline in cooking technique',
    'Brings forth traditional methods',
    'Emphasizes essential flavors',
    'Reduces excess to reveal foundation',
    'Reinforces established culinary principles',
  ],
  AspectsEffect: {
    Sun: {
      Conjunction: -0.2,
      Opposition: -0.3,
      Trine: 0.1,
      Square: -0.4,
      Sextile: 0.0,
    },
    Moon: {
      Conjunction: -0.3,
      Opposition: -0.4,
      Trine: 0.0,
      Square: -0.5,
      Sextile: -0.1,
    },
    Mercury: {
      Conjunction: -0.2,
      Opposition: -0.3,
      Trine: 0.2,
      Square: -0.3,
      Sextile: 0.1,
    },
    Jupiter: {
      Conjunction: 0.3,
      Opposition: -0.2,
      Trine: 0.4,
      Square: -0.1,
      Sextile: 0.2,
    },
    Venus: {
      Conjunction: 0.1,
      Opposition: -0.2,
      Trine: 0.3,
      Square: -0.1,
      Sextile: 0.2,
    },
    Mars: {
      Conjunction: 0.4,
      Opposition: -0.1,
      Trine: 0.3,
      Square: -0.3,
      Sextile: 0.2,
    },
  },
  PlanetSpecific: {
    ZodiacTransit: {
      Capricorn: {
        FoodFocus: 'Traditional, structured dishes with aged ingredients and earthy flavors',
        Elements: {
          Fire: 0.1,
          Earth: 0.9,
          Air: 0.2,
          Water: 0.3,
        },
        Ingredients: [
          'root vegetables',
          'aged cheese',
          'preserved meats',
          'traditional grains',
          'heirloom varieties',
          'bone broths',
        ],
      },
      Aquarius: {
        FoodFocus:
          'Innovative preservation techniques, unusual combinations of traditional ingredients',
        Elements: {
          Fire: 0.2,
          Earth: 0.3,
          Air: 0.8,
          Water: 0.1,
        },
        Ingredients: [
          'fermented foods',
          'ancient grains',
          'heritage ingredients',
          'experimental preservation',
          'structured presentations',
        ],
      },
      Libra: {
        FoodFocus: 'Balanced traditional dishes with careful attention to structure and proportion',
        Elements: {
          Fire: 0.1,
          Earth: 0.4,
          Air: 0.7,
          Water: 0.2,
        },
        Ingredients: [
          'precisely measured ingredients',
          'balanced bitter elements',
          'aged vinegars',
          'structured flavor profiles',
          'architectural presentations',
        ],
      },
      Taurus: {
        FoodFocus:
          'Disciplined earth-focused cooking with emphasis on time-honored techniques and patient preparation',
        Elements: {
          Fire: 0.1,
          Earth: 0.9,
          Air: 0.1,
          Water: 0.3,
        },
        Ingredients: [
          'dense root vegetables',
          'slow-cooked grains',
          'carefully aged dairy',
          'earthy mushrooms',
          'minerality-focused ingredients',
        ],
      },
    },
    Retrograde: {
      CulinaryEffect:
        'Revisiting traditional recipes, review of preservation techniques, slower cooking methods',
      ElementalShift: {
        Spirit: 0.7,
        Essence: 0.1,
        Matter: 0.9,
        Substance: 0.1,
      },
    },
    CulinaryTemperament: {
      EarthSaturn: {
        FoodFocus:
          'Traditional earthbound cuisine focused on preservation, aging, and structural integrity',
        Elements: {
          Fire: 0.1,
          Earth: 0.9,
          Air: 0.2,
          Water: 0.2,
        },
        Recommendations: [
          'long aging processes',
          'traditional preservation',
          'structured cooking methods',
          'disciplined techniques',
          'time-honored recipes',
        ],
      },
      AirSaturn: {
        FoodFocus:
          'Intellectual approaches to traditional cooking with systematic techniques and structured experimentation',
        Elements: {
          Fire: 0.1,
          Earth: 0.3,
          Air: 0.8,
          Water: 0.1,
        },
        Recommendations: [
          'methodical experimentation',
          'structured innovation',
          'planned cooking sequences',
          'disciplined fusion',
          'systematic approaches',
        ],
      },
    },
    CulinaryTechniques: {
      Preservation: 0.9,
      Aging: 0.9,
      'Slow Cooking': 0.8,
      Fermentation: 0.7,
      'Traditional Methods': 0.9,
    },
    TransitDates: {
      Pisces: { Start: '2023-03-07', End: '2025-05-24' },
      Aries: { Start: '2025-05-24', End: '2028-02-13' },
      Taurus: { Start: '2028-02-13', End: '2030-04-28' },
      Gemini: { Start: '2030-04-28', End: '2032-08-12' },
      Cancer: { Start: '2032-08-12', End: '2035-03-23' },
      Leo: { Start: '2035-03-23', End: '2037-06-20' },
      Virgo: { Start: '2037-06-20', End: '2039-10-14' },
      Libra: { Start: '2039-10-14', End: '2042-04-07' },
      Scorpio: { Start: '2042-04-07', End: '2044-06-21' },
      Sagittarius: { Start: '2044-06-21', End: '2046-12-22' },
      Capricorn: { Start: '2046-12-22', End: '2049-02-28' },
      Aquarius: { Start: '2049-02-28', End: '2051-06-01' },
    },
  },
}

export default saturnData
