import { PlanetData } from './types'

const venusData: PlanetData = {
  'Dignity Effect': {
    Libra: 1,
    Taurus: 1,
    Pisces: 2,
    Aries: -1,
    Scorpio: -1,
    Virgo: -2,
  },
  Elements: ['Water', 'Earth'],
  Alchemy: {
    Spirit: 0,
    Essence: 1,
    Matter: 1,
    Substance: 0,
  },
  'Diurnal Element': 'Water',
  'Nocturnal Element': 'Earth',
  AstronomicalData: {
    DistanceFromSun: '67.24 million miles (108.2 million kilometers)',
    DistanceFromEarth: {
      Minimum: '24 million miles (38 million kilometers)',
      Maximum: '162 million miles (261 million kilometers)',
    },
    Diameter: '7,521 miles (12,104 kilometers)',
    SurfaceTemperature: '900 degrees Fahrenheit (475 Celsius)',
    AtmosphericComposition: 'Primarily carbon dioxide with clouds of sulfuric acid',
    RotationPeriod: '243 Earth days (retrograde rotation)',
    OrbitPeriod: '225 Earth days',
    'Axial Tilt': '3 degrees',
    PhaseCycle: '584 days',
    SunlightTravelTime: '6 minutes',
    ZodiacalRestriction: 'Never more than 2 signs away from the Sun or Mercury',
    PhysicalCharacteristics: {
      Surface: 'Volcanoes, mountains, pancake domes, tick domes, tesserae',
      MagneticField: 'Induced magnetic field (no internal field)',
      Composition: 'Iron core, rocky mantle, thin crust',
      NotableFeatures:
        'Hottest planet, retrograde rotation, brightest object in sky after Sun and Moon',
    },
  },
  AstrologicalProperties: {
    AlchemicalName: 'Aphrodite',
    BeneficType: 'Lesser benefic',
    DualDomicile: {
      Spring: 'Taurus (yin)',
      Autumn: 'Libra (yang)',
    },
    HouseJoy: 5,
    CyclePeriod: {
      Return: 'Yearly',
      Retrograde: '40 days every 18 months',
    },
    MorningEveningStar: {
      MorningStar: 'Rising before the sun in the eastern sky',
      EveningStar: 'Visible after sunset in the western sky (during inferior conjunction)',
    },
    CoRules: ['Libra I (Sept 23-Sept 30)'],
    Exaltation: 'Pisces',
    Fall: 'Virgo',
    Detriment: ['Aries', 'Scorpio'],
    Keywords: [
      'Love',
      'Beauty',
      'Art',
      'Self-love',
      'Pleasure',
      'Music',
      'Partnerships',
      'Sensuality',
    ],
    Colors: ['Green', 'Rose', 'Emerald Green', 'Bright Rose', 'Cerise', 'Pale Green', 'Sky Blue'],
    Day: 'Friday',
    Metal: 'Copper',
    BodyParts: ['Genitals', 'Kidneys', 'Urinary system', 'Facial skin', 'Bladder', 'Throat'],
    Animals: ['Sparrow', 'Dove', 'Swan', 'Bull'],
    Stones: ['Emerald', 'Turquoise', 'Rose Quartz', 'Malachite'],
  },
  ElementalConnections: {
    DayEmission: 'Essence - "that which an object cannot exist without"',
    NightEmission: 'Matter - "that which is minimally reactive"',
    ElementalBridges: ['Connects Air to Ground', 'Connects Ground to Water'],
    SharedElements: {
      Water: ['Moon'],
      Earth: ['Mercury'],
    },
    AssociatedQualities: [
      'Moist',
      'Cool',
      'Receptive',
      'Feminine',
      'Fruitful',
      'Sweet-smelling',
      'Balance-seeking',
    ],
  },
  HerbalAssociations: {
    Herbs: [
      'Angelica',
      'Red Clover',
      "Ladies' Mantle",
      'Lemon Balm',
      'Lemon Verbena',
      'Yarrow',
      'Pennyroyal',
      'Peppermint',
      'Orris Root',
      'Tansy',
      'Myrtle',
      'Spearmint',
      'Thyme',
      'Mugwort',
      'Tonka Beans',
      'Vervain',
      'Motherwort',
      'Elder',
      'Violet',
      'Rose',
    ],
    Flowers: [
      'Rose',
      'Crocus',
      'Heather',
      'Hyacinth',
      'Violet',
      'Apple Blossom',
      'Rose Geranium',
      'Orchid',
      'Magnolia',
      'Daisy',
      'Jasmine',
      'Sweet Pea',
      'Lily of the Valley',
      'Carnation',
      'Columbine',
      'Hollyhock',
    ],
    Woods: ['Willow', 'Apple', 'Cherry'],
    Scents: [
      'Rose',
      'Vanilla',
      'Jasmine',
      'Benzoin',
      'Honeysuckle',
      'Lilac',
      'Myrtle',
      'Violet',
      'Almond',
      'Apricot',
      'Berry',
    ],
  },
  FoodAssociations: [
    'sweet fruits',
    'berries',
    'vanilla',
    'honey',
    'dairy products',
    'chocolate',
    'nuts',
    'rose water',
    'aromatic herbs',
    'edible flowers',
    'refined pastries',
    'creamy desserts',
    'soft cheeses',
    'white chocolate',
    'rose-infused foods',
    'pink foods',
    'delicate fish',
    'aphrodisiac foods',
    'balanced spice blends',
    'artfully presented dishes',
    'fine dining cuisine',
    'sweet liqueurs',
    'fruit preserves',
    'artisanal breads',
    'elegant appetizers',
    'apple',
    'raspberry',
    'strawberry',
    'pear',
    'plum',
    'apricot',
    'honey',
    'figs',
    'mango',
    'avocado',
    'fatty foods',
    'sweet potatoes',
    'plantain',
    'peach',
    'pomegranate',
    'quince',
    'coconut',
  ],
  FlavorProfiles: {
    Sweet: 0.9,
    Sour: 0.3,
    Salty: 0.2,
    Bitter: 0.1,
    Umami: 0.4,
    Spicy: 0.1,
  },
  CulinaryInfluences: [
    'Enhances sweetness and richness',
    'Balances flavors for harmony',
    'Improves texture and mouthfeel',
    'Adds aromatic qualities to dishes',
    'Supports elegant presentation',
    'Creates pleasurable eating experiences',
    'Elevates simple ingredients to luxurious dishes',
    'Encourages social dining experiences',
    'Enhances food aesthetics and beauty',
    'Fosters sensual enjoyment of food',
    'Guides indulgent yet balanced flavors',
    'Inspires artistic plating and food presentation',
    'Brings forth balanced, beautiful meals',
    'Draws toward shared sensory experiences',
    'Cultivates appreciative eating',
    'Connects cultural food traditions',
  ],
  AspectsEffect: {
    Sun: {
      Conjunction: 0.6,
      Opposition: 0.3,
      Trine: 0.5,
      Square: 0.2,
      Sextile: 0.4,
    },
    Moon: {
      Conjunction: 0.9,
      Opposition: 0.5,
      Trine: 0.8,
      Square: 0.3,
      Sextile: 0.7,
    },
    Mars: {
      Conjunction: 0.7,
      Opposition: 0.2,
      Trine: 0.5,
      Square: 0.1,
      Sextile: 0.4,
    },
    Saturn: {
      Conjunction: 0.1,
      Opposition: -0.2,
      Trine: 0.3,
      Square: -0.1,
      Sextile: 0.2,
    },
    Jupiter: {
      Conjunction: 0.8,
      Opposition: 0.3,
      Trine: 0.6,
      Square: 0.2,
      Sextile: 0.5,
    },
  },
  PlanetSpecific: {
    ZodiacTransit: {
      Aries: {
        FoodFocus:
          'Impulsive food combinations, bold yet balanced flavors, innovative presentation styles',
        Elements: {
          Fire: 0.8,
          Earth: 0.2,
          Air: 0.3,
          Water: 0.2,
        },
        Ingredients: [
          'pomegranate',
          'arugula',
          'pink peppercorns',
          'rare meats',
          'radishes',
          'chili-infused honey',
        ],
      },
      Taurus: {
        FoodFocus: 'Rich, indulgent flavors, creamy textures, and luxurious ingredients',
        Elements: {
          Fire: 0.2,
          Earth: 0.9,
          Air: 0.1,
          Water: 0.3,
        },
        Ingredients: [
          'truffle',
          'mascarpone',
          'figs',
          'artisanal butter',
          'heavy cream',
          'vanilla bean',
        ],
      },
      Gemini: {
        FoodFocus: 'Playful contrasts, dual presentations, small bites with complex layers',
        Elements: {
          Fire: 0.3,
          Earth: 0.2,
          Air: 0.8,
          Water: 0.2,
        },
        Ingredients: [
          'edible flowers',
          'microgreens',
          'paired tastings',
          'sweet and savory combinations',
          'infused oils',
          'herb-dusted dishes',
        ],
      },
      Cancer: {
        FoodFocus:
          'Comforting dishes with elegant touches, nostalgic flavors with refined presentation',
        Elements: {
          Fire: 0.1,
          Earth: 0.3,
          Air: 0.1,
          Water: 0.8,
        },
        Ingredients: [
          'crab',
          'coconut milk',
          'delicate seafood',
          'vanilla custards',
          'almond-based desserts',
          'floral teas',
        ],
      },
      Leo: {
        FoodFocus: 'Impressive, showy dishes, golden colors, luxurious and dramatic presentations',
        Elements: {
          Fire: 0.8,
          Earth: 0.2,
          Air: 0.3,
          Water: 0.1,
        },
        Ingredients: [
          'saffron',
          'golden foods',
          'honey',
          'orange blossom water',
          'high-quality olive oil',
          'edible gold',
        ],
      },
      Virgo: {
        FoodFocus: 'Precisely created dishes with health-conscious elements, purified flavors',
        Elements: {
          Fire: 0.2,
          Earth: 0.8,
          Air: 0.3,
          Water: 0.2,
        },
        Ingredients: [
          'refined grains',
          'fermented dairy',
          'subtle herbs',
          'pure honey',
          'elegant vegetable preparations',
          'delicate spices',
        ],
      },
      Libra: {
        FoodFocus: 'Balanced, elegant dishes with visual appeal and harmonious flavors',
        Elements: {
          Fire: 0.3,
          Earth: 0.2,
          Air: 0.8,
          Water: 0.3,
        },
        Ingredients: [
          'rose water',
          'balanced vinaigrettes',
          'symmetrical presentations',
          'elegant appetizers',
          'champagne',
          'pretty garnishes',
        ],
      },
      Scorpio: {
        FoodFocus:
          'Intense flavors with luxurious undertones, mysterious and sensual food experiences',
        Elements: {
          Fire: 0.4,
          Earth: 0.2,
          Air: 0.1,
          Water: 0.8,
        },
        Ingredients: [
          'dark chocolate',
          'red wine reductions',
          'black foods',
          'aphrodisiacs',
          'fermented fruits',
          'rich sauces',
        ],
      },
      Sagittarius: {
        FoodFocus: 'Internationally inspired elegant cuisine, exotic flavors with refined touches',
        Elements: {
          Fire: 0.8,
          Earth: 0.1,
          Air: 0.4,
          Water: 0.2,
        },
        Ingredients: [
          'cardamom',
          'exotic fruits',
          'refined global spices',
          'botanical liqueurs',
          'sophisticated fusion dishes',
          'elegant preserved foods',
        ],
      },
      Capricorn: {
        FoodFocus:
          'Traditional dishes with modern elegance, refined comfort foods, enduring classics',
        Elements: {
          Fire: 0.2,
          Earth: 0.8,
          Air: 0.2,
          Water: 0.3,
        },
        Ingredients: [
          'aged cheeses',
          'refined grains',
          'winter vegetables',
          'preserved fruits',
          'elegant desserts',
          'classic sauces perfected',
        ],
      },
      Aquarius: {
        FoodFocus:
          'Innovative presentations of beautiful foods, unexpected pleasant flavor combinations',
        Elements: {
          Fire: 0.3,
          Earth: 0.2,
          Air: 0.8,
          Water: 0.2,
        },
        Ingredients: [
          'unusual fruits',
          'modern culinary techniques',
          'unexpected sweet applications',
          'beautiful patterns',
          'elegant molecular gastronomy',
          'futuristic presentations',
        ],
      },
      Pisces: {
        FoodFocus:
          'Ethereal dishes with delicate flavors, dreamy presentations, otherworldly experiences',
        Elements: {
          Fire: 0.1,
          Earth: 0.1,
          Air: 0.2,
          Water: 0.9,
        },
        Ingredients: [
          'seafood carpaccio',
          'iridescent presentations',
          'delicate fish',
          'elderflower',
          'lavender',
          'subtle infusions',
        ],
      },
    },
    Retrograde: {
      CulinaryEffect:
        'Reconsideration of flavor combinations, revisiting traditional recipes with modern twists',
      ElementalShift: {
        Spirit: 0.1,
        Essence: 0.7,
        Matter: 0.6,
        Substance: 0.3,
      },
      FoodFocus:
        'Re-evaluation of favorite foods, reemerging traditional recipes, refinement of technique',
      HerbalShift:
        'Greater potency in dried herbs over fresh, intensified flavors, preserved ingredients',
    },
    TransitDates: {
      Aries: { Start: '2024-05-23', End: '2024-06-17' },
      Taurus: { Start: '2024-06-17', End: '2024-07-11' },
      Gemini: { Start: '2024-07-11', End: '2024-08-04' },
      Cancer: { Start: '2024-08-04', End: '2024-08-28' },
      Leo: { Start: '2024-08-28', End: '2024-09-22' },
      Virgo: { Start: '2024-09-22', End: '2024-10-17' },
      Libra: { Start: '2024-10-17', End: '2024-11-11' },
      Scorpio: { Start: '2024-11-11', End: '2024-12-07' },
      Sagittarius: { Start: '2024-12-07', End: '2025-01-03' },
      Capricorn: { Start: '2025-01-03', End: '2025-01-27' },
      Aquarius: { Start: '2025-01-27', End: '2025-02-20' },
      Pisces: { Start: '2025-02-20', End: '2025-03-16' },
    },
    CulinaryTechniques: {
      'Flavor Balancing': 0.9,
      'Sensory Enhancement': 0.8,
      'Aesthetic Presentation': 0.9,
      'Texture Development': 0.7,
      'Aroma Infusion': 0.8,
      'Social Dining': 0.9,
      'Indulgent Moderation': 0.7,
      'Seasonal Appreciation': 0.6,
    },
    MealTypes: {
      Breakfast: {
        Influence: 0.4,
        Recommendations: ['pastries', 'fruit parfaits', 'elegant egg dishes', 'fresh baked goods'],
      },
      Lunch: {
        Influence: 0.6,
        Recommendations: ['beautiful salads', 'light elegant fare', 'balanced flavor combinations'],
      },
      Dinner: {
        Influence: 0.8,
        Recommendations: ['multiple course meals', 'wine pairings', 'beautiful presentations'],
      },
      Dessert: {
        Influence: 0.9,
        Recommendations: ['sweet confections', 'chocolate creations', 'fruit-based indulgences'],
      },
    },
    LunarConnection: 'Dominant water-based interaction among all planets',
    CulinaryTemperament: {
      EarthVenus: {
        FoodFocus: 'Rich, indulgent flavors with stable earthy foundations',
        Recommendations: [
          'Slow-cooked dishes',
          'Root vegetables',
          'Hearty stews with refined presentation',
          'Earthy flavors with sweet notes',
        ],
      },
      AirVenus: {
        FoodFocus: 'Balanced, harmonious dishes with thoughtful presentation',
        Recommendations: [
          'Elegant small plates',
          'Visually arranged foods',
          'Balanced flavor profiles',
          'Light yet satisfying meals',
        ],
      },
    },
  },
}

export default venusData
