/* Seed data — used as fallback when live backend data is missing.
 * The chart-of-moment snapshot is replaced at runtime by useUnifiedPlanetaryPositions;
 * planetary/lunar agents are synthetic and always present.
 */

import type { ChartOfMoment, CouncilAgent, FeedEvent } from './types'

export const SEED_CHART: ChartOfMoment = {
  timestamp: new Date(),
  location: 'New York, NY · 40.71°N 74.01°W',
  planetaryHour: 'Mars',
  planetaryDay: 'Monday · Moon',
  moonPhase: 'Waxing Gibbous',
  moonIllumination: 0.78,
  dominantPlanet: 'Mars',
  dominantSign: 'Scorpio',
  dominantElement: 'Fire',
  rulerReason: 'Mars in domicile · current planetary hour',
  positions: [
    { planet: 'Sun', sign: 'Taurus', degree: 28.4, retrograde: false, dignity: 'peregrine' },
    { planet: 'Moon', sign: 'Libra', degree: 12.1, retrograde: false, dignity: 'peregrine' },
    { planet: 'Mercury', sign: 'Taurus', degree: 15.7, retrograde: false, dignity: 'peregrine' },
    { planet: 'Venus', sign: 'Aries', degree: 6.2, retrograde: false, dignity: 'detriment' },
    { planet: 'Mars', sign: 'Scorpio', degree: 14.0, retrograde: false, dignity: 'domicile' },
    { planet: 'Jupiter', sign: 'Cancer', degree: 3.5, retrograde: false, dignity: 'exaltation' },
    { planet: 'Saturn', sign: 'Pisces', degree: 28.9, retrograde: false, dignity: 'peregrine' },
    { planet: 'Uranus', sign: 'Gemini', degree: 2.8, retrograde: false, dignity: 'peregrine' },
    { planet: 'Neptune', sign: 'Aries', degree: 4.1, retrograde: false, dignity: 'peregrine' },
    { planet: 'Pluto', sign: 'Aquarius', degree: 3.7, retrograde: true, dignity: 'peregrine' },
  ],
  aspects: [
    { a: 'Mars', b: 'Jupiter', type: 'sextile', orb: 0.8, applying: true, intensity: 0.85 },
    { a: 'Sun', b: 'Saturn', type: 'sextile', orb: 2.1, applying: false, intensity: 0.45 },
    { a: 'Venus', b: 'Neptune', type: 'conjunction', orb: 2.1, applying: true, intensity: 0.95 },
    { a: 'Moon', b: 'Mars', type: 'opposition', orb: 1.9, applying: true, intensity: 0.8 },
    { a: 'Mercury', b: 'Pluto', type: 'square', orb: 3.5, applying: false, intensity: 0.5 },
  ],
  thermodynamics: { heat: 0.62, entropy: 0.81, reactivity: 0.74, energy: 0.18, aNumber: 7.43 },
  elemental: { Fire: 38, Water: 27, Earth: 18, Air: 17 },
}

/* Synthetic agents — ruler-of-the-moment + active lunar — always present. */
export const PLANETARY_AGENT: CouncilAgent = {
  id: 'mars-scorpio-14',
  name: 'Mars in Scorpio 14°',
  kind: 'planetary',
  planet: 'Mars',
  sun: 'Scorpio',
  natal: [{ planet: 'Mars', sign: 'Scorpio', degree: 14 }],
  elemental: { Fire: 62, Water: 28, Earth: 6, Air: 4 },
  esms: { spirit: 9, essence: 4, matter: 7, substance: 3 },
  monicaConstant: 5.5,
  kalchm: 12.4,
  stats: {
    power: 96,
    resonance: 58,
    wisdom: 60,
    charisma: 72,
    intuition: 66,
    adaptability: 70,
    vitality: 92,
  },
  planetary12: {
    solarAgency: 60,
    lunarReceptivity: 40,
    mercurialVelocity: 70,
    venusianCoherence: 50,
    martialImpetus: 100,
    jovianExpansion: 60,
    saturnianStructure: 60,
    chironicAdaptation: 60,
    uranianSurprisal: 50,
    neptunianResonance: 50,
    plutonicIntegration: 80,
    kineticAlignment: 90,
  },
  specialty: 'martial impetus · domicile authority',
  evolutionLevel: 'transcendent',
  consciousness: 'Transcendent',
  cooldown: 0,
  dignity: 'domicile',
  isRulerOfMoment: true,
}

export const LUNAR_AGENT: CouncilAgent = {
  id: 'waxing-gibbous-moon',
  name: 'Waxing Gibbous Moon',
  kind: 'lunar',
  planet: 'Moon',
  sun: 'Libra',
  natal: [{ planet: 'Moon', sign: 'Libra', degree: 12 }],
  elemental: { Fire: 12, Water: 54, Earth: 18, Air: 16 },
  esms: { spirit: 3, essence: 9, matter: 4, substance: 6 },
  monicaConstant: 5.0,
  kalchm: 5.83,
  stats: {
    power: 64,
    resonance: 84,
    wisdom: 70,
    charisma: 78,
    intuition: 92,
    adaptability: 86,
    vitality: 72,
  },
  planetary12: {
    solarAgency: 60,
    lunarReceptivity: 96,
    mercurialVelocity: 72,
    venusianCoherence: 80,
    martialImpetus: 54,
    jovianExpansion: 74,
    saturnianStructure: 64,
    chironicAdaptation: 80,
    uranianSurprisal: 58,
    neptunianResonance: 92,
    plutonicIntegration: 68,
    kineticAlignment: 78,
  },
  specialty: 'refinement · culmination preview',
  evolutionLevel: 'gold',
  consciousness: 'Mastered',
  cooldown: 0,
}

/* Seed feed events — bootstrap for first-paint until the live stream takes over. */
const m = (mins: number) => new Date(Date.now() - mins * 60000).toISOString()

export const SEED_FEED_EVENTS: FeedEvent[] = [
  {
    id: 'transit-001',
    type: 'planetary-degree',
    timestamp: m(8),
    agentId: 'mars-scorpio-14',
    planet: 'Mars',
    sign: 'Scorpio',
    degree: 14,
    previousDegree: 13,
    dignity: 'domicile',
    element: 'Water',
    modality: 'Fixed',
    title: 'Mars entered 14° Scorpio',
    body: 'Mars consolidates power in its own house. The current planetary hour amplifies martial impetus. Agents with Fire ≥ 30% gain +15% Meltdown intensity for the next 60 minutes.',
    rulerEvent: true,
  },
  {
    id: 'aspect-001',
    type: 'aspect-activation',
    timestamp: m(14),
    aspect: { a: 'Venus', b: 'Neptune', type: 'conjunction', orb: 2.1 },
    activates: [],
    title: 'Venus ☌ Neptune · activating Resonance lattice',
    body: 'Agents with high Venusian Coherence AND Neptunian Resonance can now cast paired moves at reduced cost.',
    discount: 0.4,
  },
  {
    id: 'insight-002',
    type: 'insight',
    timestamp: m(88),
    agentId: 'waxing-gibbous-moon',
    title: 'Waxing Gibbous in Libra · refinement window',
    body: 'For the human nervous system: the Moon is in the courtroom phase. Use this transit for negotiating with what is almost-decided. Keep the action small enough to finish before the Moon changes mood again.',
    confidence: 0.85,
  },
]
